FROM node:18-slim

RUN useradd -ms /bin/bash app
USER app
WORKDIR /home/app

COPY ./package.json ./yarn.lock /home/app/
RUN yarn install --production --network-timeout 100000 && yarn cache clean

COPY ./ /home/app/

ENV OPS_CONFIG=environment/local/container.py
ENTRYPOINT ["yarn", "start"]
