FROM node:20-slim
RUN useradd -ms /bin/bash app
USER app
WORKDIR /home/app

COPY --chown=app:app ./package.json ./yarn.lock /home/app/
RUN yarn install --production --network-timeout 100000 && yarn cache clean

COPY --chown=app:app ./ /home/app/

CMD ["yarn", "start"]
