#!/bin/bash
# Detects flaky E2E tests by parsing Cypress output for retry patterns
# Usage: detect-flaky-tests.sh <cypress_output_file> [github_summary_file]
#
# This script identifies spec files that had retry attempts, which may indicate
# flakiness. Results are formatted for GitHub Actions job summaries.

set -euo pipefail

# Input validation
if [ $# -lt 1 ]; then
    echo "Usage: $0 <cypress_output_file> [github_summary_file]"
    echo ""
    echo "Example: $0 cypress.log \$GITHUB_STEP_SUMMARY"
    exit 1
fi

CYPRESS_LOG="$1"
GITHUB_SUMMARY="${2:-}"

# Check if input file exists
if [ ! -f "$CYPRESS_LOG" ]; then
    echo "Error: Cypress output file not found: $CYPRESS_LOG"
    exit 1
fi

# Temporary file for results
FLAKY_TESTS=$(mktemp)
trap 'rm -f "$FLAKY_TESTS"' EXIT

# Parse Cypress output for retry patterns
# Look for lines with "Attempt X of Y" which indicate retries
# These lines also contain the spec file name
grep -E "Attempt [2-9] of [0-9]" "$CYPRESS_LOG" | \
    awk '{
        # Find the field containing .cy.js (the spec filename)
        for(i=1; i<=NF; i++) {
            if($i ~ /\.cy\.js/) {
                # Extract just the filename without directory path
                spec = $i
                sub(/.*\//, "", spec)
                print spec
                break
            }
        }
    }' | \
    sort -u > "$FLAKY_TESTS" 2>/dev/null || true

# Count flaky tests
FLAKY_COUNT=$(wc -l < "$FLAKY_TESTS" | tr -d ' ')

# Generate report
generate_report() {
    echo "## 🔄 Flaky Test Detection Report"
    echo ""

    if [ "$FLAKY_COUNT" -eq 0 ]; then
        echo "✅ **No flaky tests detected!**"
        echo ""
        echo "All tests passed on first attempt."
    else
        echo "⚠️ **$FLAKY_COUNT spec file(s) with retries detected**"
        echo ""
        echo "The following spec files had retry attempts (indicating potential flakiness):"
        echo ""
        echo "| Spec File |"
        echo "|-----------|"

        while IFS= read -r spec; do
            echo "| \`$spec\` |"
        done < "$FLAKY_TESTS"

        echo ""
        echo "### What does this mean?"
        echo ""
        echo "These spec files were retried during the test run. This may indicate:"
        echo "- **Test flakiness**: Non-deterministic test behavior"
        echo "- **Possible causes**: Timing issues, race conditions, external dependencies, or test pollution"
        echo ""
        echo "### Recommended Actions"
        echo ""
        echo "1. **Review the test**: Examine the spec file for timing-dependent assertions"
        echo "2. **Check for race conditions**: Look for async operations without proper waits"
        echo "3. **Consider tagging**: If consistently flaky, tag with \`@flaky\` for tracking"
        echo "4. **Investigate CI logs**: Review screenshots and stack traces in artifacts"
        echo ""
        echo "### Tracking Flaky Tests"
        echo ""
        echo "To track known flaky tests, consider using cypress-grep:"
        echo "\`\`\`javascript"
        echo "it('test name @flaky', () => { ... })"
        echo "\`\`\`"
    fi

    echo ""
    echo "---"
    echo "*Generated by flaky test detection* • $(date '+%Y-%m-%d %H:%M:%S %Z')"
}

# Output to console
generate_report

# Output to GitHub Actions job summary if specified
if [ -n "$GITHUB_SUMMARY" ]; then
    generate_report >> "$GITHUB_SUMMARY"
fi

# Exit with appropriate code
if [ "$FLAKY_COUNT" -gt 0 ]; then
    echo ""
    echo "⚠️  Warning: $FLAKY_COUNT flaky test(s) detected"
    # Don't fail the job, just warn
    exit 0
else
    exit 0
fi
