@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name getAllCans
GET http://{{host}}/ops/cans HTTP/1.1
content-type: @{{contentType}}

###

# @name getCanById
GET http://{{host}}/ops/cans/1 HTTP/1.1
content-type: application/json

###

# @name admin
GET http://{{host}}/admin HTTP/1.1
