@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name getAllCans
GET http://{{host}}/ops/cans HTTP/1.1
content-type: @{{contentType}}

###

# @name getCanById
GET http://{{host}}/ops/cans/1 HTTP/1.1
content-type: application/json

###

# @name admin
GET http://{{host}}/admin HTTP/1.1

###

# @name getCanFiscalYear
GET http://{{host}}/ops/cfys HTTP/1.1
content-type: @{{contentType}}

###

# @name getCanFiscalYearById
GET http://{{host}}/ops/cfy/5 HTTP/1.1
content-type: @{{contentType}}

###

# @name getCanFiscalYearByCan
GET http://{{host}}/ops/cfys/3/2022 HTTP/1.1
content-type: @{{contentType}}
