FROM python:3.10-slim

LABEL org.opencontainers.image.description="OPRE-OPS API Python Base"
LABEL org.opencontainers.image.licenses=CC0-1.0
# hadolint ignore=DL3008
RUN apt-get update && apt-get -y install curl --no-install-recommends && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip==22.3.1 pipenv==2023.3.20 && useradd -ms /bin/bash app

# perform additional hardening steps here
# TODO: harden image.
