sequenceDiagram
    autonumber
    participant User
    participant GUI as OPS Web
    participant API as OPS API
    participant DB as OPS DB

    GUI ->> GUI: Display BLI Review Card

    User ->>+ GUI: User verifies the data looks correct, and clicks "Create BLI" button
    GUI ->>+ API: Post /budget-line-items

    API ->> API: Validate BLI POST data is correct.
    API ->>+ DB: Store BLI-Created-Event
    DB ->>- API: return history status

    API ->>+ DB: Set version on object in history

    API ->>+ GUI: Return HTTP response

    GUI ->> GUI: Page redirects to BLI Dashboard
