[pytest]
pythonpath = . ..
testpaths = tests
bdd_features_base_dir = tests/ops/features/
addopts = -p no:cacheprovider
filterwarnings =
    ignore:nested transaction already deassociated from connection:sqlalchemy.exc.SAWarning
    ignore:At least one scoped session is already present:sqlalchemy.exc.SAWarning
