name: Set up Javascript
description: Installs Bun.js and dependencies defined in package.json
runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
      with:
        bun-version: latest
    - name: Install bun dependencies
      shell: bash
      working-directory: ./frontend
      run: bun install
