"""add change_request owning division

Revision ID: 8983993c4454
Revises: 1fa3d063b893
Create Date: 2024-05-28 21:50:47.481285+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8983993c4454'
down_revision: Union[str, None] = '1fa3d063b893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_request', sa.Column('owning_division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'change_request', 'division', ['owning_division_id'], ['id'])
    op.add_column('change_request_version', sa.Column('owning_division_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_request_version', 'owning_division_id')
    op.drop_constraint(None, 'change_request', type_='foreignkey')
    op.drop_column('change_request', 'owning_division_id')
    # ### end Alembic commands ###
