"""add ProcurmentTracker and remove dependency on workflow

Revision ID: bca30c6d60b5
Revises: c98733f2a098
Create Date: 2024-07-29 17:19:23.250434+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'bca30c6d60b5'
down_revision: Union[str, None] = 'c98733f2a098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('current_step_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['current_step_id'], ['procurement_step.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_tracker_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('current_step_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_procurement_tracker_version_end_transaction_id'), 'procurement_tracker_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_operation_type'), 'procurement_tracker_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_transaction_id'), 'procurement_tracker_version', ['transaction_id'], unique=False)
    op.add_column('procurement_step', sa.Column('procurement_tracker_id', sa.Integer(), nullable=True))
    op.drop_constraint('procurement_step_workflow_step_id_fkey', 'procurement_step', type_='foreignkey')
    op.create_foreign_key(None, 'procurement_step', 'procurement_tracker', ['procurement_tracker_id'], ['id'])
    op.drop_column('procurement_step', 'workflow_step_id')
    op.add_column('procurement_step_version', sa.Column('procurement_tracker_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('procurement_step_version', 'workflow_step_id')
    op.sync_enum_values('ops', 'opseventtype', ['CREATE_BLI', 'UPDATE_BLI', 'DELETE_BLI', 'SEND_BLI_FOR_APPROVAL', 'CREATE_PROJECT', 'CREATE_NEW_AGREEMENT', 'UPDATE_AGREEMENT', 'DELETE_AGREEMENT', 'ACKNOWLEDGE_NOTIFICATION', 'CREATE_BLI_PACKAGE', 'UPDATE_BLI_PACKAGE', 'CREATE_SERVICES_COMPONENT', 'UPDATE_SERVICES_COMPONENT', 'DELETE_SERVICES_COMPONENT', 'CREATE_PROCUREMENT_ACQUISITION_PLANNING', 'UPDATE_PROCUREMENT_ACQUISITION_PLANNING', 'DELETE_PROCUREMENT_ACQUISITION_PLANNING', 'CREATE_DOCUMENT', 'LOGIN_ATTEMPT', 'LOGOUT', 'GET_USER_DETAILS', 'CREATE_USER', 'UPDATE_USER', 'DEACTIVATE_USER'],
                        [TableReference(table_schema='ops', table_name='ops_event', column_name='event_type'), TableReference(table_schema='ops', table_name='ops_event_version', column_name='event_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('ops', 'opseventtype', ['LOGIN_ATTEMPT', 'CREATE_BLI', 'UPDATE_BLI', 'DELETE_BLI', 'CREATE_PROJECT', 'CREATE_NEW_AGREEMENT', 'UPDATE_AGREEMENT', 'SEND_BLI_FOR_APPROVAL', 'DELETE_AGREEMENT', 'ACKNOWLEDGE_NOTIFICATION', 'LOGOUT', 'CREATE_USER', 'UPDATE_USER', 'DEACTIVATE_USER', 'CREATE_BLI_PACKAGE', 'UPDATE_BLI_PACKAGE', 'CREATE_SERVICES_COMPONENT', 'UPDATE_SERVICES_COMPONENT', 'DELETE_SERVICES_COMPONENT', 'CREATE_PROCUREMENT_ACQUISITION_PLANNING', 'UPDATE_PROCUREMENT_ACQUISITION_PLANNING', 'DELETE_PROCUREMENT_ACQUISITION_PLANNING', 'CREATE_DOCUMENT'],
                        [TableReference(table_schema='ops', table_name='ops_event', column_name='event_type'), TableReference(table_schema='ops', table_name='ops_event_version', column_name='event_type')],
                        enum_values_to_rename=[])
    op.add_column('procurement_step_version', sa.Column('workflow_step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('procurement_step_version', 'procurement_tracker_id')
    op.add_column('procurement_step', sa.Column('workflow_step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'procurement_step', type_='foreignkey')
    op.create_foreign_key('procurement_step_workflow_step_id_fkey', 'procurement_step', 'workflow_step_instance', ['workflow_step_id'], ['id'])
    op.drop_column('procurement_step', 'procurement_tracker_id')
    op.drop_index(op.f('ix_procurement_tracker_version_transaction_id'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_operation_type'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_end_transaction_id'), table_name='procurement_tracker_version')
    op.drop_table('procurement_tracker_version')
    op.drop_table('procurement_tracker')
    # ### end Alembic commands ###
