"""add user status

Revision ID: fee4f0523601
Revises: 48a9bca44782
Create Date: 2024-03-04 15:21:43.561239+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee4f0523601'
down_revision: Union[str, None] = '48a9bca44782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED', name='userstatus'), nullable=False))
    op.add_column('user_version', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED', name='userstatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_version', 'status')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
