"""enum for change request type

Revision ID: 0cdc149783cd
Revises: c4323133b35b
Create Date: 2024-06-18 13:50:37.409956+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cdc149783cd'
down_revision: Union[str, None] = 'c4323133b35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CHANGE_REQUEST', 'AGREEMENT_CHANGE_REQUEST', 'BUDGET_LINE_ITEM_CHANGE_REQUEST', name='changerequesttype').create(op.get_bind())
    op.add_column('change_request', sa.Column('change_request_type', postgresql.ENUM('CHANGE_REQUEST', 'AGREEMENT_CHANGE_REQUEST', 'BUDGET_LINE_ITEM_CHANGE_REQUEST', name='changerequesttype', create_type=False), nullable=False))
    op.drop_column('change_request', 'type')
    op.add_column('change_request_version', sa.Column('change_request_type', postgresql.ENUM('CHANGE_REQUEST', 'AGREEMENT_CHANGE_REQUEST', 'BUDGET_LINE_ITEM_CHANGE_REQUEST', name='changerequesttype', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('change_request_version', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_request_version', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('change_request_version', 'change_request_type')
    op.add_column('change_request', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('change_request', 'change_request_type')
    sa.Enum('CHANGE_REQUEST', 'AGREEMENT_CHANGE_REQUEST', 'BUDGET_LINE_ITEM_CHANGE_REQUEST', name='changerequesttype').drop(op.get_bind())
    # ### end Alembic commands ###
