"""Adding contract category to contract agreement

Revision ID: d849b102901c
Revises: d0582f1a0924
Create Date: 2024-06-26 15:12:19.684670+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd849b102901c'
down_revision: Union[str, None] = 'd0582f1a0924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('RESEARCH', 'SERVICE', name='contractcategory').create(op.get_bind())
    op.add_column('contract_agreement', sa.Column('contract_category', postgresql.ENUM('RESEARCH', 'SERVICE', name='contractcategory', create_type=False), nullable=True))
    op.add_column('contract_agreement_version', sa.Column('contract_category', postgresql.ENUM('RESEARCH', 'SERVICE', name='contractcategory', create_type=False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_agreement_version', 'contract_category')
    op.drop_column('contract_agreement', 'contract_category')
    sa.Enum('RESEARCH', 'SERVICE', name='contractcategory').drop(op.get_bind())
    # ### end Alembic commands ###
