"""add PROCUREMENT_TRACKING to WorkflowAction Enum

Revision ID: 6c85c1668a9f
Revises: 7b0f215948a8
Create Date: 2024-03-13 19:47:44.457355+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6c85c1668a9f'
down_revision: Union[str, None] = '7b0f215948a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('ops', 'workflowaction', ['DRAFT_TO_PLANNED', 'PLANNED_TO_EXECUTING', 'GENERIC', 'PROCUREMENT_TRACKING'],
                        [TableReference(table_schema='ops', table_name='workflow_instance', column_name='workflow_action'), TableReference(table_schema='ops', table_name='workflow_instance_version', column_name='workflow_action')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('ops', 'workflowaction', ['DRAFT_TO_PLANNED', 'PLANNED_TO_EXECUTING', 'GENERIC'],
                        [TableReference(table_schema='ops', table_name='workflow_instance', column_name='workflow_action'), TableReference(table_schema='ops', table_name='workflow_instance_version', column_name='workflow_action')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
