"""Adding on-hold, certified, and closed to BLI

Revision ID: 5d3916a592a6
Revises: d411fa4a071b
Create Date: 2024-07-15 21:16:10.634028+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d3916a592a6'
down_revision: Union[str, None] = 'd411fa4a071b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_line_item', sa.Column('on_hold', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('budget_line_item', sa.Column('certified', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('budget_line_item', sa.Column('closed', sa.Boolean(), nullable=False, server_default='f'))
    op.add_column('budget_line_item_version', sa.Column('on_hold', sa.Boolean(), autoincrement=False, nullable=True, server_default='f'))
    op.add_column('budget_line_item_version', sa.Column('certified', sa.Boolean(), autoincrement=False, nullable=True, server_default='f'))
    op.add_column('budget_line_item_version', sa.Column('closed', sa.Boolean(), autoincrement=False, nullable=True, server_default='f'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_line_item_version', 'closed')
    op.drop_column('budget_line_item_version', 'certified')
    op.drop_column('budget_line_item_version', 'on_hold')
    op.drop_column('budget_line_item', 'closed')
    op.drop_column('budget_line_item', 'certified')
    op.drop_column('budget_line_item', 'on_hold')
    # ### end Alembic commands ###
