"""add ChangeRequestNotification subclass

Revision ID: 151465a54d91
Revises: 4bbe5ac187f2
Create Date: 2024-07-17 15:08:11.677407+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '151465a54d91'
down_revision: Union[str, None] = '4bbe5ac187f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOTIFICATION', 'CHANGE_REQUEST_NOTIFICATION', name='notificationtype').create(op.get_bind())
    op.add_column('notification', sa.Column('notification_type', postgresql.ENUM('NOTIFICATION', 'CHANGE_REQUEST_NOTIFICATION', name='notificationtype', create_type=False), nullable=False))
    op.add_column('notification', sa.Column('change_request_id', sa.Integer(), nullable=True))
    op.alter_column('notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'notification', 'change_request', ['change_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('notification_version', sa.Column('notification_type', postgresql.ENUM('NOTIFICATION', 'CHANGE_REQUEST_NOTIFICATION', name='notificationtype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('notification_version', sa.Column('change_request_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_version', 'change_request_id')
    op.drop_column('notification_version', 'notification_type')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.alter_column('notification', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('notification', 'change_request_id')
    op.drop_column('notification', 'notification_type')
    sa.Enum('NOTIFICATION', 'CHANGE_REQUEST_NOTIFICATION', name='notificationtype').drop(op.get_bind())
    # ### end Alembic commands ###
