"""Add DELETE_BLI to OpsEventType Enum

Revision ID: 7b0f215948a8
Revises: 2f078ae6d0fb
Create Date: 2024-03-11 22:01:26.969203+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '7b0f215948a8'
down_revision: Union[str, None] = '2f078ae6d0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('ops', 'opseventtype', ['LOGIN_ATTEMPT', 'CREATE_BLI', 'UPDATE_BLI', 'DELETE_BLI', 'CREATE_PROJECT', 'CREATE_NEW_AGREEMENT', 'UPDATE_AGREEMENT', 'SEND_BLI_FOR_APPROVAL', 'DELETE_AGREEMENT', 'ACKNOWLEDGE_NOTIFICATION', 'LOGOUT', 'CREATE_USER', 'UPDATE_USER', 'DEACTIVATE_USER', 'CREATE_BLI_PACKAGE', 'UPDATE_BLI_PACKAGE', 'CREATE_SERVICES_COMPONENT', 'UPDATE_SERVICES_COMPONENT', 'DELETE_SERVICES_COMPONENT', 'CREATE_PROCUREMENT_ACQUISITION_PLANNING', 'UPDATE_PROCUREMENT_ACQUISITION_PLANNING', 'DELETE_PROCUREMENT_ACQUISITION_PLANNING'],
                        [TableReference(table_schema='ops', table_name='ops_event_version', column_name='event_type'), TableReference(table_schema='ops', table_name='ops_event', column_name='event_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('ops', 'opseventtype', ['LOGIN_ATTEMPT', 'CREATE_BLI', 'UPDATE_BLI', 'CREATE_PROJECT', 'CREATE_NEW_AGREEMENT', 'UPDATE_AGREEMENT', 'SEND_BLI_FOR_APPROVAL', 'DELETE_AGREEMENT', 'ACKNOWLEDGE_NOTIFICATION', 'LOGOUT', 'CREATE_USER', 'UPDATE_USER', 'DEACTIVATE_USER', 'CREATE_BLI_PACKAGE', 'UPDATE_BLI_PACKAGE', 'CREATE_SERVICES_COMPONENT', 'UPDATE_SERVICES_COMPONENT', 'DELETE_SERVICES_COMPONENT', 'CREATE_PROCUREMENT_ACQUISITION_PLANNING', 'UPDATE_PROCUREMENT_ACQUISITION_PLANNING', 'DELETE_PROCUREMENT_ACQUISITION_PLANNING'],
                        [TableReference(table_schema='ops', table_name='ops_event_version', column_name='event_type'), TableReference(table_schema='ops', table_name='ops_event', column_name='event_type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
