"""add can_fiscal_year_funding_details

Revision ID: 186e5faae7ee
Revises: cfdfddab1d80
Create Date: 2024-07-01 22:38:33.001320+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '186e5faae7ee'
down_revision: Union[str, None] = 'cfdfddab1d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('can_fiscal_year_funding_details_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('fund', sa.String(length=14), autoincrement=False, nullable=True),
    sa.Column('allowance', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('sub_allowance', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('allotment_org', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('current_fy_funding_ytd', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('can_fiscal_year_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_can_fiscal_year_funding_details_version_end_transaction_id'), 'can_fiscal_year_funding_details_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_can_fiscal_year_funding_details_version_operation_type'), 'can_fiscal_year_funding_details_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_can_fiscal_year_funding_details_version_transaction_id'), 'can_fiscal_year_funding_details_version', ['transaction_id'], unique=False)
    op.create_table('can_fiscal_year_funding_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund', sa.String(length=14), nullable=True),
    sa.Column('allowance', sa.String(length=10), nullable=True),
    sa.Column('sub_allowance', sa.String(length=10), nullable=True),
    sa.Column('allotment_org', sa.String(length=10), nullable=True),
    sa.Column('current_fy_funding_ytd', sa.Integer(), nullable=True),
    sa.Column('can_fiscal_year_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['can_fiscal_year_id'], ['can_fiscal_year.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'can_fiscal_year', ['can_id', 'fiscal_year'])
    op.alter_column('can_fiscal_year_version', 'can_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('can_fiscal_year_version', 'can_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.drop_constraint(None, 'can_fiscal_year', type_='unique')
    op.drop_table('can_fiscal_year_funding_details')
    op.drop_index(op.f('ix_can_fiscal_year_funding_details_version_transaction_id'), table_name='can_fiscal_year_funding_details_version')
    op.drop_index(op.f('ix_can_fiscal_year_funding_details_version_operation_type'), table_name='can_fiscal_year_funding_details_version')
    op.drop_index(op.f('ix_can_fiscal_year_funding_details_version_end_transaction_id'), table_name='can_fiscal_year_funding_details_version')
    op.drop_table('can_fiscal_year_funding_details_version')
    # ### end Alembic commands ###
