"""add change_request managing division

Revision ID: 60dc9b968f32
Revises: 1fa3d063b893
Create Date: 2024-05-29 16:47:39.290972+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60dc9b968f32'
down_revision: Union[str, None] = '1fa3d063b893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_request', sa.Column('managing_division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'change_request', 'division', ['managing_division_id'], ['id'])
    op.add_column('change_request_version', sa.Column('managing_division_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_request_version', 'managing_division_id')
    op.drop_constraint(None, 'change_request', type_='foreignkey')
    op.drop_column('change_request', 'managing_division_id')
    # ### end Alembic commands ###
