"""cascade_delete_services_components

Revision ID: 8999cd8548cd
Revises: 48a9bca44782
Create Date: 2024-03-04 22:51:55.040951+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8999cd8548cd"
down_revision: Union[str, None] = "2622c803ce1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services_component",
        "contract_agreement_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "services_component_contract_agreement_id_fkey",
        "services_component",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "services_component",
        "contract_agreement",
        ["contract_agreement_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services_component", type_="foreignkey")
    op.create_foreign_key(
        "services_component_contract_agreement_id_fkey",
        "services_component",
        "contract_agreement",
        ["contract_agreement_id"],
        ["id"],
    )
    op.alter_column(
        "services_component",
        "contract_agreement_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
