"""Remove incumbent from contract agreement. Prefer to use Vendor instead

Revision ID: 6615ac7d4eea
Revises: af64d84afb2e
Create Date: 2024-10-28 19:47:50.822292+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6615ac7d4eea'
down_revision: Union[str, None] = 'af64d84afb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_agreement_incumbent_id_fkey', 'contract_agreement', type_='foreignkey')
    op.drop_column('contract_agreement', 'incumbent_id')
    op.drop_column('contract_agreement_version', 'incumbent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_agreement_version', sa.Column('incumbent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contract_agreement', sa.Column('incumbent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contract_agreement_incumbent_id_fkey', 'contract_agreement', 'vendor', ['incumbent_id'], ['id'])
    # ### end Alembic commands ###
