"""renaming column for direct obligations--2148

Revision ID: 99b44a4926e8
Revises: ff7132d9d0c0
Create Date: 2024-04-08 04:49:02.334180+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99b44a4926e8'
down_revision: Union[str, None] = 'ff7132d9d0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_agreement', sa.Column('direct_receiving_partner', sa.String(), nullable=False))
    op.drop_column('direct_agreement', 'payee')
    op.add_column('direct_agreement_version', sa.Column('direct_receiving_partner', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('direct_agreement_version', 'payee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_agreement_version', sa.Column('payee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('direct_agreement_version', 'direct_receiving_partner')
    op.add_column('direct_agreement', sa.Column('payee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('direct_agreement', 'direct_receiving_partner')
    # ### end Alembic commands ###
