"""procurement workflow changes

Revision ID: 2f078ae6d0fb
Revises: 8999cd8548cd
Create Date: 2024-03-05 21:19:16.272216+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f078ae6d0fb'
down_revision: Union[str, None] = '8999cd8548cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_step_instance', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('workflow_step_instance_version', sa.Column('index', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_step_instance_version', 'index')
    op.drop_column('workflow_step_instance', 'index')
    # ### end Alembic commands ###
