"""Adding external_authorizer_id property

Revision ID: aa5783297a09
Revises: 1d92818fa69b
Create Date: 2024-07-11 18:31:45.107498+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa5783297a09'
down_revision: Union[str, None] = '1d92818fa69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('can', sa.Column('external_authorizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'can', 'contact', ['external_authorizer_id'], ['id'])
    op.add_column('can_version', sa.Column('external_authorizer_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('can_version', 'external_authorizer_id')
    op.drop_constraint(None, 'can', type_='foreignkey')
    op.drop_column('can', 'external_authorizer_id')
    # ### end Alembic commands ###
