"""update CAN model part 2

Revision ID: 84a1c2255779
Revises: eb4261420779
Create Date: 2024-08-26 21:56:32.454418+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84a1c2255779'
down_revision: Union[str, None] = 'eb4261420779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('can_funding_budget', sa.Column('can_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'can_funding_budget', ['fiscal_year', 'can_id'])
    op.create_foreign_key(None, 'can_funding_budget', 'can', ['can_id'], ['id'])
    op.drop_column('can_funding_budget', 'fund_code')
    op.add_column('can_funding_budget_version', sa.Column('can_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('can_funding_budget_version', 'fund_code')
    op.add_column('can_funding_received', sa.Column('can_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'can_funding_received', 'can', ['can_id'], ['id'])
    op.drop_column('can_funding_received', 'fund_code')
    op.add_column('can_funding_received_version', sa.Column('can_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('can_funding_received_version', 'fund_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('can_funding_received_version', sa.Column('fund_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('can_funding_received_version', 'can_id')
    op.add_column('can_funding_received', sa.Column('fund_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'can_funding_received', type_='foreignkey')
    op.drop_column('can_funding_received', 'can_id')
    op.add_column('can_funding_budget_version', sa.Column('fund_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('can_funding_budget_version', 'can_id')
    op.add_column('can_funding_budget', sa.Column('fund_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'can_funding_budget', type_='foreignkey')
    op.drop_constraint(None, 'can_funding_budget', type_='unique')
    op.drop_column('can_funding_budget', 'can_id')
    # ### end Alembic commands ###
