"""update procurement shop unique constraint

Revision ID: 39ed81adb783
Revises: 608b001a0415
Create Date: 2025-05-26 19:14:00.476246+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39ed81adb783'
down_revision: Union[str, None] = '608b001a0415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('procurement_shop_fee_unique_active_period'), 'procurement_shop_fee', type_='unique')
    op.create_unique_constraint('procurement_shop_fee_unique_active_period', 'procurement_shop_fee', ['procurement_shop_id', 'start_date', 'end_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('procurement_shop_fee_unique_active_period', 'procurement_shop_fee', type_='unique')
    op.create_unique_constraint(op.f('procurement_shop_fee_unique_active_period'), 'procurement_shop_fee', ['procurement_shop_id', 'end_date'])
    # ### end Alembic commands ###
