"""clin and mod number optional

Revision ID: 0fdbce05f036
Revises: 8bebcdd110dd
Create Date: 2025-03-13 21:04:30.994632+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fdbce05f036'
down_revision: Union[str, None] = '8bebcdd110dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_mod', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agreement_mod', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
