"""Adding research methodology and special topics to agreement base model

Revision ID: 440d8a3d81ea
Revises: 52da2ba214cd
Create Date: 2025-11-12 20:42:40.081109+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440d8a3d81ea'
down_revision: Union[str, None] = '52da2ba214cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_research_methodologies_version',
    sa.Column('research_methodology_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('research_methodology_id', 'agreement_id', 'transaction_id')
    )
    op.create_index(op.f('ix_agreement_research_methodologies_version_end_transaction_id'), 'agreement_research_methodologies_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_agreement_research_methodologies_version_operation_type'), 'agreement_research_methodologies_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_agreement_research_methodologies_version_transaction_id'), 'agreement_research_methodologies_version', ['transaction_id'], unique=False)
    op.create_table('agreement_research_methodologies',
    sa.Column('research_methodology_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['research_methodology_id'], ['research_methodology.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('research_methodology_id', 'agreement_id')
    )
    op.add_column('agreement', sa.Column('special_topics_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agreement', 'special_topics', ['special_topics_id'], ['id'])
    op.add_column('agreement_version', sa.Column('special_topics_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreement_version', 'special_topics_id')
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.drop_column('agreement', 'special_topics_id')
    op.drop_table('agreement_research_methodologies')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_transaction_id'), table_name='agreement_research_methodologies_version')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_operation_type'), table_name='agreement_research_methodologies_version')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_end_transaction_id'), table_name='agreement_research_methodologies_version')
    op.drop_table('agreement_research_methodologies_version')
    # ### end Alembic commands ###
