"""Add detailed_name field to research_methodology

Revision ID: 08af75126345
Revises: 5b89d517ea94
Create Date: 2025-12-17 16:20:28.836613+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08af75126345'
down_revision: Union[str, None] = '5b89d517ea94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_methodology', sa.Column('detailed_name', sa.String(), nullable=False))
    op.add_column('research_methodology_version', sa.Column('detailed_name', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_methodology_version', 'detailed_name')
    op.drop_column('research_methodology', 'detailed_name')
    # ### end Alembic commands ###
