"""Set SC ID to NULL on delete in BudgetLineItem

Revision ID: 30d78efe9773
Revises: 52da2ba214cd
Create Date: 2025-11-12 15:34:43.567282+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30d78efe9773"
down_revision: Union[str, None] = "52da2ba214cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("budget_line_item_services_component_id_fkey"),
        "budget_line_item",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "budget_line_item_services_component_id_fkey",
        "budget_line_item",
        "services_component",
        ["services_component_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("services_component_number_sub_component_optional_agreement__key"),
        "services_component",
        type_="unique",
    )
    op.create_index(
        "ix_services_component_unique_null_subcomponent",
        "services_component",
        ["agreement_id", "number", "optional"],
        unique=True,
        postgresql_where=sa.text("sub_component IS NULL"),
    )
    op.create_index(
        "ix_services_component_unique_with_subcomponent",
        "services_component",
        ["agreement_id", "number", "sub_component", "optional"],
        unique=True,
        postgresql_where=sa.text("sub_component IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_services_component_unique_with_subcomponent",
        table_name="services_component",
        postgresql_where=sa.text("sub_component IS NOT NULL"),
    )
    op.drop_index(
        "ix_services_component_unique_null_subcomponent",
        table_name="services_component",
        postgresql_where=sa.text("sub_component IS NULL"),
    )
    op.create_unique_constraint(
        op.f("services_component_number_sub_component_optional_agreement__key"),
        "services_component",
        ["number", "sub_component", "optional", "agreement_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "budget_line_item_services_component_id_fkey",
        "budget_line_item",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("budget_line_item_services_component_id_fkey"),
        "budget_line_item",
        "services_component",
        ["services_component_id"],
        ["id"],
    )
    # ### end Alembic commands ###
