"""remove payee from direct_agreement

Revision ID: 486929593d89
Revises: 8cae71e65c45
Create Date: 2025-03-24 15:09:41.578389+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "486929593d89"
down_revision: Union[str, None] = "f8b2a2a8b484"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("direct_agreement", "payee")
    op.drop_column("direct_agreement_version", "payee")
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_obligation_budget_line_item",
        sa.Column("receiving_agency", sa.String(), nullable=True),
    )
    op.add_column(
        "direct_obligation_budget_line_item",
        sa.Column("ip_nbr", sa.String(), nullable=True),
    )
    op.add_column(
        "direct_obligation_budget_line_item_version",
        sa.Column("receiving_agency", sa.String(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "direct_obligation_budget_line_item_version",
        sa.Column("ip_nbr", sa.String(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("direct_obligation_budget_line_item_version", "ip_nbr")
    op.drop_column("direct_obligation_budget_line_item_version", "receiving_agency")
    op.drop_column("direct_obligation_budget_line_item", "ip_nbr")
    op.drop_column("direct_obligation_budget_line_item", "receiving_agency")
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_agreement_version",
        sa.Column("payee", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "direct_agreement",
        sa.Column("payee", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
