"""move service_requirement_type to agreement

Revision ID: a62f33014a89
Revises: 76e2039458d9
Create Date: 2025-08-14 15:43:17.573892+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62f33014a89'
down_revision: Union[str, None] = '76e2039458d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aa_agreement', 'service_requirement_type')
    op.drop_column('aa_agreement_version', 'service_requirement_type')
    op.add_column('agreement', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), nullable=True))
    op.add_column('agreement_version', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('contract_agreement', 'service_requirement_type')
    op.drop_column('contract_agreement_version', 'service_requirement_type')
    op.add_column('services_component', sa.Column('agreement_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('services_component_number_sub_component_optional_contract_a_key'), 'services_component', type_='unique')
    op.create_unique_constraint(None, 'services_component', ['number', 'sub_component', 'optional', 'agreement_id'])
    op.drop_constraint(op.f('services_component_contract_agreement_id_fkey'), 'services_component', type_='foreignkey')
    op.create_foreign_key(None, 'services_component', 'agreement', ['agreement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('services_component', 'contract_agreement_id')
    op.add_column('services_component_version', sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=True))
    op.drop_column('services_component_version', 'contract_agreement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_component_version', sa.Column('contract_agreement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('services_component_version', 'agreement_id')
    op.add_column('services_component', sa.Column('contract_agreement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services_component', type_='foreignkey')
    op.create_foreign_key(op.f('services_component_contract_agreement_id_fkey'), 'services_component', 'contract_agreement', ['contract_agreement_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'services_component', type_='unique')
    op.create_unique_constraint(op.f('services_component_number_sub_component_optional_contract_a_key'), 'services_component', ['number', 'sub_component', 'optional', 'contract_agreement_id'])
    op.drop_column('services_component', 'agreement_id')
    op.add_column('contract_agreement_version', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('contract_agreement', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('agreement_version', 'service_requirement_type')
    op.drop_column('agreement', 'service_requirement_type')
    op.add_column('aa_agreement_version', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('aa_agreement', sa.Column('service_requirement_type', postgresql.ENUM('SEVERABLE', 'NON_SEVERABLE', name='servicerequirementtype', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
