"""add procurement actions

Revision ID: 5b89d517ea94
Revises: d8f34037b656
Create Date: 2025-12-11 17:46:24.485861+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b89d517ea94'
down_revision: Union[str, None] = 'd8f34037b656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ===== DATA CLEANUP =====
    # Clear existing requisition data before schema changes.
    # Requisitions are being moved from BudgetLineItem to ProcurementAction.
    # Since ProcurementAction is a new model, there are no existing
    # ProcurementActions to link requisitions to, so we must clear existing
    # requisition records to avoid orphaned data.
    op.execute('DELETE FROM requisition')
    op.execute('DELETE FROM requisition_version')
    # ===== END DATA CLEANUP =====

    sa.Enum('PLANNED', 'REQUISITION_SUBMITTED', 'IN_PROCESS', 'AWARDED', 'CERTIFIED', 'CANCELLED', name='procurementactionstatus').create(op.get_bind())
    sa.Enum('NEW_AWARD', 'MODIFICATION', 'NEW_TASK_ORDER', 'EXERCISE_OPTION_AS_IS', 'FOLLOW_ON', 'SIMPLIFIED_ACQUISITION', 'MICRO_PURCHASE', 'ADMINISTRATIVE', name='awardtype').create(op.get_bind())
    sa.Enum('INITIAL', 'FINAL', name='requisitiontype').create(op.get_bind())
    op.create_table('procurement_action_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('agreement_mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('award_type', postgresql.ENUM('NEW_AWARD', 'MODIFICATION', 'NEW_TASK_ORDER', 'EXERCISE_OPTION_AS_IS', 'FOLLOW_ON', 'SIMPLIFIED_ACQUISITION', 'MICRO_PURCHASE', 'ADMINISTRATIVE', name='awardtype', create_type=False), autoincrement=False, nullable=True),
    sa.Column('mod_type', postgresql.ENUM('NEW', 'ADMIN', 'AMOUNT_TBD', 'AS_IS', 'REPLACEMENT_AMOUNT_FINAL', name='modtype', create_type=False), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'REQUISITION_SUBMITTED', 'IN_PROCESS', 'AWARDED', 'CERTIFIED', 'CANCELLED', name='procurementactionstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('procurement_shop_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('psc_action_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('need_by_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('requisition_deadline', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('date_awarded_obligated', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('desired_days_on_street', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('action_description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('psc_fee_percentage', sa.Numeric(precision=12, scale=5), autoincrement=False, nullable=True),
    sa.Column('award_total', sa.Numeric(precision=12, scale=2), autoincrement=False, nullable=True, comment='Official award amount for this procurement action'),
    sa.Column('agreement_total', sa.Numeric(precision=12, scale=2), autoincrement=False, nullable=True, comment='Cumulative agreement total after this action'),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_procurement_action_version_end_transaction_id'), 'procurement_action_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_action_version_operation_type'), 'procurement_action_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_action_version_transaction_id'), 'procurement_action_version', ['transaction_id'], unique=False)
    op.create_table('procurement_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('agreement_mod_id', sa.Integer(), nullable=True),
    sa.Column('award_type', postgresql.ENUM('NEW_AWARD', 'MODIFICATION', 'NEW_TASK_ORDER', 'EXERCISE_OPTION_AS_IS', 'FOLLOW_ON', 'SIMPLIFIED_ACQUISITION', 'MICRO_PURCHASE', 'ADMINISTRATIVE', name='awardtype', create_type=False), nullable=True),
    sa.Column('mod_type', postgresql.ENUM('NEW', 'ADMIN', 'AMOUNT_TBD', 'AS_IS', 'REPLACEMENT_AMOUNT_FINAL', name='modtype', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('PLANNED', 'REQUISITION_SUBMITTED', 'IN_PROCESS', 'AWARDED', 'CERTIFIED', 'CANCELLED', name='procurementactionstatus', create_type=False), nullable=True),
    sa.Column('procurement_shop_id', sa.Integer(), nullable=True),
    sa.Column('psc_action_number', sa.String(), nullable=True),
    sa.Column('need_by_date', sa.Date(), nullable=True),
    sa.Column('requisition_deadline', sa.Date(), nullable=True),
    sa.Column('date_awarded_obligated', sa.Date(), nullable=True),
    sa.Column('desired_days_on_street', sa.Integer(), nullable=True),
    sa.Column('action_description', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('psc_fee_percentage', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('award_total', sa.Numeric(precision=12, scale=2), nullable=True, comment='Official award amount for this procurement action'),
    sa.Column('agreement_total', sa.Numeric(precision=12, scale=2), nullable=True, comment='Cumulative agreement total after this action'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['agreement_mod_id'], ['agreement_mod.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['procurement_shop_id'], ['procurement_shop.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('budget_line_item', sa.Column('procurement_action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budget_line_item', 'procurement_action', ['procurement_action_id'], ['id'])
    op.add_column('budget_line_item_version', sa.Column('procurement_action_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('requisition', sa.Column('procurement_action_id', sa.Integer(), nullable=True))
    op.add_column('requisition', sa.Column('type', postgresql.ENUM('INITIAL', 'FINAL', name='requisitiontype', create_type=False), nullable=True))
    op.drop_constraint(op.f('requisition_budget_line_item_id_fkey'), 'requisition', type_='foreignkey')
    op.create_foreign_key(None, 'requisition', 'procurement_action', ['procurement_action_id'], ['id'])
    op.drop_column('requisition', 'budget_line_item_id')
    op.add_column('requisition_version', sa.Column('procurement_action_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('requisition_version', sa.Column('type', postgresql.ENUM('INITIAL', 'FINAL', name='requisitiontype', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('requisition_version', 'budget_line_item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisition_version', sa.Column('budget_line_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('requisition_version', 'type')
    op.drop_column('requisition_version', 'procurement_action_id')
    op.add_column('requisition', sa.Column('budget_line_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requisition', type_='foreignkey')
    op.create_foreign_key(op.f('requisition_budget_line_item_id_fkey'), 'requisition', 'budget_line_item', ['budget_line_item_id'], ['id'])
    op.drop_column('requisition', 'type')
    op.drop_column('requisition', 'procurement_action_id')
    op.drop_column('budget_line_item_version', 'procurement_action_id')
    op.drop_constraint(None, 'budget_line_item', type_='foreignkey')
    op.drop_column('budget_line_item', 'procurement_action_id')
    op.drop_table('procurement_action')
    op.drop_index(op.f('ix_procurement_action_version_transaction_id'), table_name='procurement_action_version')
    op.drop_index(op.f('ix_procurement_action_version_operation_type'), table_name='procurement_action_version')
    op.drop_index(op.f('ix_procurement_action_version_end_transaction_id'), table_name='procurement_action_version')
    op.drop_table('procurement_action_version')
    sa.Enum('INITIAL', 'FINAL', name='requisitiontype').drop(op.get_bind())
    sa.Enum('NEW_AWARD', 'MODIFICATION', 'NEW_TASK_ORDER', 'EXERCISE_OPTION_AS_IS', 'FOLLOW_ON', 'SIMPLIFIED_ACQUISITION', 'MICRO_PURCHASE', 'ADMINISTRATIVE', name='awardtype').drop(op.get_bind())
    sa.Enum('PLANNED', 'REQUISITION_SUBMITTED', 'IN_PROCESS', 'AWARDED', 'CERTIFIED', 'CANCELLED', name='procurementactionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
