"""remove constraint from project short_title

Revision ID: c9a2b729be0e
Revises: baeefc8305f1
Create Date: 2025-02-03 15:49:36.094504+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c9a2b729be0e'
down_revision: Union[str, None] = 'baeefc8305f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'short_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('project_short_title_key', 'project', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_short_title_key', 'project', ['short_title'])
    op.alter_column('project', 'short_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
