"""Adding special topics and research methodology to agreement model

Revision ID: b280a042b68f
Revises: 30d78efe9773
Create Date: 2025-11-17 22:10:04.963969+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b280a042b68f'
down_revision: Union[str, None] = '30d78efe9773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreement_research_methodologies_version',
    sa.Column('research_methodology_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('research_methodology_id', 'agreement_id', 'transaction_id')
    )
    op.create_index(op.f('ix_agreement_research_methodologies_version_end_transaction_id'), 'agreement_research_methodologies_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_agreement_research_methodologies_version_operation_type'), 'agreement_research_methodologies_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_agreement_research_methodologies_version_transaction_id'), 'agreement_research_methodologies_version', ['transaction_id'], unique=False)
    op.create_table('agreement_special_topics_version',
    sa.Column('special_topic_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('special_topic_id', 'agreement_id', 'transaction_id')
    )
    op.create_index(op.f('ix_agreement_special_topics_version_end_transaction_id'), 'agreement_special_topics_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_agreement_special_topics_version_operation_type'), 'agreement_special_topics_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_agreement_special_topics_version_transaction_id'), 'agreement_special_topics_version', ['transaction_id'], unique=False)
    op.create_table('agreement_research_methodologies',
    sa.Column('research_methodology_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['research_methodology_id'], ['research_methodology.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('research_methodology_id', 'agreement_id')
    )
    op.create_table('agreement_special_topics',
    sa.Column('special_topic_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['special_topic_id'], ['special_topics.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('special_topic_id', 'agreement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agreement_special_topics')
    op.drop_table('agreement_research_methodologies')
    op.drop_index(op.f('ix_agreement_special_topics_version_transaction_id'), table_name='agreement_special_topics_version')
    op.drop_index(op.f('ix_agreement_special_topics_version_operation_type'), table_name='agreement_special_topics_version')
    op.drop_index(op.f('ix_agreement_special_topics_version_end_transaction_id'), table_name='agreement_special_topics_version')
    op.drop_table('agreement_special_topics_version')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_transaction_id'), table_name='agreement_research_methodologies_version')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_operation_type'), table_name='agreement_research_methodologies_version')
    op.drop_index(op.f('ix_agreement_research_methodologies_version_end_transaction_id'), table_name='agreement_research_methodologies_version')
    op.drop_table('agreement_research_methodologies_version')
    # ### end Alembic commands ###
