"""add props to aa bli

Revision ID: 76e2039458d9
Revises: 808b957abe3f
Create Date: 2025-07-22 21:27:32.053725+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '76e2039458d9'
down_revision: Union[str, None] = '808b957abe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aa_budget_line_item', sa.Column('mod_id', sa.Integer(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('psc_fee_doc_number', sa.String(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('psc_fee_pymt_ref_nbr', sa.String(), nullable=True))
    op.create_foreign_key(None, 'aa_budget_line_item', 'agreement_mod', ['mod_id'], ['id'])
    op.add_column('aa_budget_line_item_version', sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('psc_fee_doc_number', sa.String(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('psc_fee_pymt_ref_nbr', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aa_budget_line_item_version', 'psc_fee_pymt_ref_nbr')
    op.drop_column('aa_budget_line_item_version', 'psc_fee_doc_number')
    op.drop_column('aa_budget_line_item_version', 'mod_id')
    op.drop_constraint(None, 'aa_budget_line_item', type_='foreignkey')
    op.drop_column('aa_budget_line_item', 'psc_fee_pymt_ref_nbr')
    op.drop_column('aa_budget_line_item', 'psc_fee_doc_number')
    op.drop_column('aa_budget_line_item', 'mod_id')
    # ### end Alembic commands ###
