"""update_bli_status

Revision ID: 35527bc8640d
Revises: 10064745b084
Create Date: 2025-06-09 18:26:39.668021+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '35527bc8640d'
down_revision: Union[str, None] = '10064745b084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='ops',
        enum_name='budgetlineitemstatus',
        new_values=['DRAFT', 'PLANNED', 'IN_EXECUTION', 'OBLIGATED', 'OVERCOME_BY_EVENTS'],
        affected_columns=[TableReference(table_schema='ops', table_name='budget_line_item', column_name='status'), TableReference(table_schema='ops', table_name='budget_line_item_version', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='ops',
        enum_name='budgetlineitemstatus',
        new_values=['DRAFT', 'PLANNED', 'IN_EXECUTION', 'OBLIGATED'],
        affected_columns=[TableReference(table_schema='ops', table_name='budget_line_item', column_name='status'), TableReference(table_schema='ops', table_name='budget_line_item_version', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
