"""adding fiscal year to CANHistory

Revision ID: 3d8237681112
Revises: c9a2b729be0e
Create Date: 2025-02-06 21:33:56.555892+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d8237681112'
down_revision: Union[str, None] = 'c9a2b729be0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('can_history', sa.Column('fiscal_year', sa.Integer(), nullable=False))
    op.add_column('can_history_version', sa.Column('fiscal_year', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('can_history_version', 'fiscal_year')
    op.drop_column('can_history', 'fiscal_year')
    # ### end Alembic commands ###
