"""Removing fiscal year column from table

Revision ID: 8b805e161b62
Revises: 3d8237681112
Create Date: 2025-02-12 19:37:57.430420+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8b805e161b62'
down_revision: Union[str, None] = '3d8237681112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('can_history', 'fiscal_year')
    op.drop_column('can_history_version', 'fiscal_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('can_history_version', sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('can_history', sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
