"""move grant details to grant bli model

Revision ID: 89175beb9f35
Revises: 248f7f768c8c
Create Date: 2025-03-06 20:07:01.823663+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '89175beb9f35'
down_revision: Union[str, None] = '248f7f768c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant_budget_line_item', sa.Column('details_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grant_budget_line_item', 'grant_budget_line_item_detail', ['details_id'], ['id'])
    op.drop_constraint('grant_budget_line_item_detail_agreement_id_fkey', 'grant_budget_line_item_detail', type_='foreignkey')
    op.drop_column('grant_budget_line_item_detail', 'agreement_id')
    op.drop_column('grant_budget_line_item_detail_version', 'agreement_id')
    op.add_column('grant_budget_line_item_version', sa.Column('details_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grant_budget_line_item_version', 'details_id')
    op.add_column('grant_budget_line_item_detail_version', sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grant_budget_line_item_detail', sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('grant_budget_line_item_detail_agreement_id_fkey', 'grant_budget_line_item_detail', 'agreement', ['agreement_id'], ['id'])
    op.drop_constraint(None, 'grant_budget_line_item', type_='foreignkey')
    op.drop_column('grant_budget_line_item', 'details_id')
    # ### end Alembic commands ###
