"""add iaa_customer_agency;add attributes to IAA and IAA BLI

Revision ID: 8cae71e65c45
Revises: 0fdbce05f036
Create Date: 2025-03-19 22:31:34.864800+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cae71e65c45'
down_revision: Union[str, None] = '0fdbce05f036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # manually added
    sa.Sequence("iaa_customer_agency_id_seq", start=100, increment=1).create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INCOMING', 'OUTGOING', name='iaadirectiontype').create(op.get_bind())
    op.create_table('iaa_budget_line_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ip_nbr', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_iaa_budget_line_item_version_end_transaction_id'), 'iaa_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_iaa_budget_line_item_version_operation_type'), 'iaa_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_iaa_budget_line_item_version_transaction_id'), 'iaa_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_table('iaa_customer_agency_contacts_version',
    sa.Column('iaa_customer_agency_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('iaa_customer_agency_id', 'contact_id', 'transaction_id')
    )
    op.create_index(op.f('ix_iaa_customer_agency_contacts_version_end_transaction_id'), 'iaa_customer_agency_contacts_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_iaa_customer_agency_contacts_version_operation_type'), 'iaa_customer_agency_contacts_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_iaa_customer_agency_contacts_version_transaction_id'), 'iaa_customer_agency_contacts_version', ['transaction_id'], unique=False)
    op.create_table('iaa_customer_agency_version',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('iaa_customer_agency_id_seq')"), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('customer_duns', sa.String(), autoincrement=False, nullable=True),
    sa.Column('object_class_code_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('customer_agency_nbr', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_iaa_customer_agency_version_end_transaction_id'), 'iaa_customer_agency_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_iaa_customer_agency_version_operation_type'), 'iaa_customer_agency_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_iaa_customer_agency_version_transaction_id'), 'iaa_customer_agency_version', ['transaction_id'], unique=False)
    op.create_table('iaa_customer_agency',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('iaa_customer_agency_id_seq')"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer_duns', sa.String(), nullable=True),
    sa.Column('object_class_code_id', sa.Integer(), nullable=True),
    sa.Column('customer_agency_nbr', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['object_class_code_id'], ['object_class_code.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaa_customer_agency_contacts',
    sa.Column('iaa_customer_agency_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['iaa_customer_agency_id'], ['iaa_customer_agency.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('iaa_customer_agency_id', 'contact_id')
    )
    op.create_table('iaa_budget_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_nbr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_iaaa_budget_line_item_version_end_transaction_id', table_name='iaaa_budget_line_item_version')
    op.drop_index('ix_iaaa_budget_line_item_version_operation_type', table_name='iaaa_budget_line_item_version')
    op.drop_index('ix_iaaa_budget_line_item_version_transaction_id', table_name='iaaa_budget_line_item_version')
    op.drop_table('iaaa_budget_line_item_version')
    op.drop_table('iaaa_budget_line_item')
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('iaa_agreement', sa.Column('direction', postgresql.ENUM('INCOMING', 'OUTGOING', name='iaadirectiontype', create_type=False), nullable=False))
    op.add_column('iaa_agreement', sa.Column('iaa_customer_agency_id', sa.Integer(), nullable=True))
    op.add_column('iaa_agreement', sa.Column('opre_poc', sa.String(), nullable=True))
    op.add_column('iaa_agreement', sa.Column('agency_poc', sa.String(), nullable=True))
    op.create_foreign_key(None, 'iaa_agreement', 'iaa_customer_agency', ['iaa_customer_agency_id'], ['id'])
    op.drop_column('iaa_agreement', 'iaa')
    op.add_column('iaa_agreement_version', sa.Column('direction', postgresql.ENUM('INCOMING', 'OUTGOING', name='iaadirectiontype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('iaa_agreement_version', sa.Column('iaa_customer_agency_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('iaa_agreement_version', sa.Column('opre_poc', sa.String(), autoincrement=False, nullable=True))
    op.add_column('iaa_agreement_version', sa.Column('agency_poc', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('iaa_agreement_version', 'iaa')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_line_item', sa.Column('proc_shop_fee_percentage', sa.Numeric(precision=12, scale=5), nullable=True))
    op.add_column('budget_line_item_version', sa.Column('proc_shop_fee_percentage', sa.Numeric(precision=12, scale=5), autoincrement=False, nullable=True))
    op.drop_column('contract_budget_line_item', 'proc_shop_fee_percentage')
    op.drop_column('contract_budget_line_item_version', 'proc_shop_fee_percentage')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # manually added
    op.drop_sequence('iaa_customer_agency_id_seq')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_budget_line_item_version', sa.Column('proc_shop_fee_percentage', sa.NUMERIC(precision=12, scale=5), autoincrement=False, nullable=True))
    op.add_column('contract_budget_line_item', sa.Column('proc_shop_fee_percentage', sa.NUMERIC(precision=12, scale=5), autoincrement=False, nullable=True))
    op.drop_column('budget_line_item_version', 'proc_shop_fee_percentage')
    op.drop_column('budget_line_item', 'proc_shop_fee_percentage')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iaa_agreement_version', sa.Column('iaa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('iaa_agreement_version', 'agency_poc')
    op.drop_column('iaa_agreement_version', 'opre_poc')
    op.drop_column('iaa_agreement_version', 'iaa_customer_agency_id')
    op.drop_column('iaa_agreement_version', 'direction')
    op.add_column('iaa_agreement', sa.Column('iaa', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'iaa_agreement', type_='foreignkey')
    op.drop_column('iaa_agreement', 'agency_poc')
    op.drop_column('iaa_agreement', 'opre_poc')
    op.drop_column('iaa_agreement', 'iaa_customer_agency_id')
    op.drop_column('iaa_agreement', 'direction')
    op.alter_column('clin', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('iaaa_budget_line_item',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], name='iaaa_budget_line_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='iaaa_budget_line_item_pkey')
    )
    op.create_table('iaaa_budget_line_item_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='iaaa_budget_line_item_version_pkey')
    )
    op.create_index('ix_iaaa_budget_line_item_version_transaction_id', 'iaaa_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_index('ix_iaaa_budget_line_item_version_operation_type', 'iaaa_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index('ix_iaaa_budget_line_item_version_end_transaction_id', 'iaaa_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.drop_table('iaa_budget_line_item')
    op.drop_table('iaa_customer_agency_contacts')
    op.drop_table('iaa_customer_agency')
    op.drop_index(op.f('ix_iaa_customer_agency_version_transaction_id'), table_name='iaa_customer_agency_version')
    op.drop_index(op.f('ix_iaa_customer_agency_version_operation_type'), table_name='iaa_customer_agency_version')
    op.drop_index(op.f('ix_iaa_customer_agency_version_end_transaction_id'), table_name='iaa_customer_agency_version')
    op.drop_table('iaa_customer_agency_version')
    op.drop_index(op.f('ix_iaa_customer_agency_contacts_version_transaction_id'), table_name='iaa_customer_agency_contacts_version')
    op.drop_index(op.f('ix_iaa_customer_agency_contacts_version_operation_type'), table_name='iaa_customer_agency_contacts_version')
    op.drop_index(op.f('ix_iaa_customer_agency_contacts_version_end_transaction_id'), table_name='iaa_customer_agency_contacts_version')
    op.drop_table('iaa_customer_agency_contacts_version')
    op.drop_index(op.f('ix_iaa_budget_line_item_version_transaction_id'), table_name='iaa_budget_line_item_version')
    op.drop_index(op.f('ix_iaa_budget_line_item_version_operation_type'), table_name='iaa_budget_line_item_version')
    op.drop_index(op.f('ix_iaa_budget_line_item_version_end_transaction_id'), table_name='iaa_budget_line_item_version')
    op.drop_table('iaa_budget_line_item_version')
    sa.Enum('INCOMING', 'OUTGOING', name='iaadirectiontype').drop(op.get_bind())
    # ### end Alembic commands ###
