"""removed obe status with obe boolean attribute

Revision ID: 00a7e0543939
Revises: 35527bc8640d
Create Date: 2025-06-26 18:24:55.244544+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '00a7e0543939'
down_revision: Union[str, None] = '35527bc8640d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_line_item', sa.Column('is_obe', sa.Boolean(), nullable=False))
    op.add_column('budget_line_item_version', sa.Column('is_obe', sa.Boolean(), autoincrement=False, nullable=True))
    op.sync_enum_values(
        enum_schema='ops',
        enum_name='budgetlineitemstatus',
        new_values=['DRAFT', 'PLANNED', 'IN_EXECUTION', 'OBLIGATED'],
        affected_columns=[TableReference(table_schema='ops', table_name='budget_line_item', column_name='status'), TableReference(table_schema='ops', table_name='budget_line_item_version', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='ops',
        enum_name='budgetlineitemstatus',
        new_values=['DRAFT', 'PLANNED', 'IN_EXECUTION', 'OBLIGATED', 'OVERCOME_BY_EVENTS'],
        affected_columns=[TableReference(table_schema='ops', table_name='budget_line_item', column_name='status'), TableReference(table_schema='ops', table_name='budget_line_item_version', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_column('budget_line_item_version', 'is_obe')
    op.drop_column('budget_line_item', 'is_obe')
    # ### end Alembic commands ###
