"""duns optional

Revision ID: 8bebcdd110dd
Revises: 89175beb9f35
Create Date: 2025-03-12 19:02:00.057215+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bebcdd110dd'
down_revision: Union[str, None] = '89175beb9f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'duns',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'duns',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
