"""add props to aa bli;update relationships on sc and clin

Revision ID: a17cf0a735c7
Revises: 808b957abe3f
Create Date: 2025-07-22 14:00:44.977488+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a17cf0a735c7'
down_revision: Union[str, None] = '808b957abe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aa_budget_line_item', sa.Column('services_component_id', sa.Integer(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('clin_id', sa.Integer(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('mod_id', sa.Integer(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('psc_fee_doc_number', sa.String(), nullable=True))
    op.add_column('aa_budget_line_item', sa.Column('psc_fee_pymt_ref_nbr', sa.String(), nullable=True))
    op.create_foreign_key(None, 'aa_budget_line_item', 'services_component', ['services_component_id'], ['id'])
    op.create_foreign_key(None, 'aa_budget_line_item', 'clin', ['clin_id'], ['id'])
    op.create_foreign_key(None, 'aa_budget_line_item', 'agreement_mod', ['mod_id'], ['id'])
    op.add_column('aa_budget_line_item_version', sa.Column('services_component_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('clin_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('psc_fee_doc_number', sa.String(), autoincrement=False, nullable=True))
    op.add_column('aa_budget_line_item_version', sa.Column('psc_fee_pymt_ref_nbr', sa.String(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aa_budget_line_item_version', 'psc_fee_pymt_ref_nbr')
    op.drop_column('aa_budget_line_item_version', 'psc_fee_doc_number')
    op.drop_column('aa_budget_line_item_version', 'mod_id')
    op.drop_column('aa_budget_line_item_version', 'clin_id')
    op.drop_column('aa_budget_line_item_version', 'services_component_id')
    op.drop_constraint(None, 'aa_budget_line_item', type_='foreignkey')
    op.drop_constraint(None, 'aa_budget_line_item', type_='foreignkey')
    op.drop_constraint(None, 'aa_budget_line_item', type_='foreignkey')
    op.drop_column('aa_budget_line_item', 'psc_fee_pymt_ref_nbr')
    op.drop_column('aa_budget_line_item', 'psc_fee_doc_number')
    op.drop_column('aa_budget_line_item', 'mod_id')
    op.drop_column('aa_budget_line_item', 'clin_id')
    op.drop_column('aa_budget_line_item', 'services_component_id')
    # ### end Alembic commands ###
