"""unique agreement name and agreement type

Revision ID: 77d93b9a5595
Revises: a1b2c3d4e5f6
Create Date: 2025-12-04 19:36:27.447444+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d93b9a5595'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agreement_name_type_lower', 'agreement', ['name', 'agreement_type'], unique=True, postgresql_ops={'name': 'lower'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agreement_name_type_lower', table_name='agreement', postgresql_ops={'name': 'lower'})
    # ### end Alembic commands ###
