"""remove payee from direct_agreement

Revision ID: 486929593d89
Revises: 8cae71e65c45
Create Date: 2025-03-24 15:09:41.578389+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '486929593d89'
down_revision: Union[str, None] = '8cae71e65c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_agreement', 'payee')
    op.drop_column('direct_agreement_version', 'payee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_agreement_version', sa.Column('payee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('direct_agreement', sa.Column('payee', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
