"""update AgreementMod.mod_date to Optional

Revision ID: 04e9785794ca
Revises: 8c9a30d8d6b4
Create Date: 2025-02-19 15:08:48.806684+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04e9785794ca'
down_revision: Union[str, None] = '8c9a30d8d6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_mod', 'mod_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_mod', 'mod_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
