"""add polymorphic types for blis

Revision ID: 248f7f768c8c
Revises: b5d03aa79d12
Create Date: 2025-02-27 16:37:56.938161+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248f7f768c8c'
down_revision: Union[str, None] = 'b5d03aa79d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'AS', 'GU', 'MP', 'PR', 'VI', name='statecode').create(op.get_bind())
    op.create_table('contract_budget_line_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('services_component_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('clin_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('mod_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('psc_fee_doc_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('psc_fee_pymt_ref_nbr', sa.String(), autoincrement=False, nullable=True),
    sa.Column('proc_shop_fee_percentage', sa.Numeric(precision=12, scale=5), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_contract_budget_line_item_version_end_transaction_id'), 'contract_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_contract_budget_line_item_version_operation_type'), 'contract_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_contract_budget_line_item_version_transaction_id'), 'contract_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_table('direct_obligation_budget_line_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_direct_obligation_budget_line_item_version_end_transaction_id'), 'direct_obligation_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_direct_obligation_budget_line_item_version_operation_type'), 'direct_obligation_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_direct_obligation_budget_line_item_version_transaction_id'), 'direct_obligation_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_table('grant_budget_line_item_detail_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('grants_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('grantee_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('educational_institution', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('state_code', postgresql.ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'AS', 'GU', 'MP', 'PR', 'VI', name='statecode', create_type=False), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_grant_budget_line_item_detail_version_end_transaction_id'), 'grant_budget_line_item_detail_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_grant_budget_line_item_detail_version_operation_type'), 'grant_budget_line_item_detail_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_grant_budget_line_item_detail_version_transaction_id'), 'grant_budget_line_item_detail_version', ['transaction_id'], unique=False)
    op.create_table('grant_budget_line_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('grant_year_number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('bns_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('committed_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('fa_signed_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_grant_budget_line_item_version_end_transaction_id'), 'grant_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_grant_budget_line_item_version_operation_type'), 'grant_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_grant_budget_line_item_version_transaction_id'), 'grant_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_table('iaaa_budget_line_item_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_iaaa_budget_line_item_version_end_transaction_id'), 'iaaa_budget_line_item_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_iaaa_budget_line_item_version_operation_type'), 'iaaa_budget_line_item_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_iaaa_budget_line_item_version_transaction_id'), 'iaaa_budget_line_item_version', ['transaction_id'], unique=False)
    op.create_table('grant_budget_line_item_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=True),
    sa.Column('grants_number', sa.String(), nullable=True),
    sa.Column('grantee_name', sa.String(), nullable=True),
    sa.Column('educational_institution', sa.Boolean(), nullable=True),
    sa.Column('state_code', postgresql.ENUM('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'AS', 'GU', 'MP', 'PR', 'VI', name='statecode', create_type=False), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_obligation_budget_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_budget_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_year_number', sa.Integer(), nullable=True),
    sa.Column('bns_number', sa.String(), nullable=True),
    sa.Column('committed_date', sa.Date(), nullable=True),
    sa.Column('fa_signed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaaa_budget_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_budget_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('services_component_id', sa.Integer(), nullable=True),
    sa.Column('clin_id', sa.Integer(), nullable=True),
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('psc_fee_doc_number', sa.String(), nullable=True),
    sa.Column('psc_fee_pymt_ref_nbr', sa.String(), nullable=True),
    sa.Column('proc_shop_fee_percentage', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['clin_id'], ['clin.id'], ),
    sa.ForeignKeyConstraint(['id'], ['budget_line_item.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['agreement_mod.id'], ),
    sa.ForeignKeyConstraint(['services_component_id'], ['services_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('budget_line_item', sa.Column('budget_line_item_type', postgresql.ENUM('CONTRACT', 'GRANT', 'DIRECT_OBLIGATION', 'IAA', 'IAA_AA', 'MISCELLANEOUS', name='agreementtype', create_type=False), nullable=False))
    op.drop_constraint('budget_line_item_mod_id_fkey', 'budget_line_item', type_='foreignkey')
    op.drop_constraint('budget_line_item_clin_id_fkey', 'budget_line_item', type_='foreignkey')
    op.drop_constraint('budget_line_item_services_component_id_fkey', 'budget_line_item', type_='foreignkey')
    op.drop_column('budget_line_item', 'services_component_id')
    op.drop_column('budget_line_item', 'psc_fee_pymt_ref_nbr')
    op.drop_column('budget_line_item', 'proc_shop_fee_percentage')
    op.drop_column('budget_line_item', 'mod_id')
    op.drop_column('budget_line_item', 'psc_fee_doc_number')
    op.drop_column('budget_line_item', 'clin_id')
    op.add_column('budget_line_item_version', sa.Column('budget_line_item_type', postgresql.ENUM('CONTRACT', 'GRANT', 'DIRECT_OBLIGATION', 'IAA', 'IAA_AA', 'MISCELLANEOUS', name='agreementtype', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('budget_line_item_version', 'services_component_id')
    op.drop_column('budget_line_item_version', 'psc_fee_pymt_ref_nbr')
    op.drop_column('budget_line_item_version', 'proc_shop_fee_percentage')
    op.drop_column('budget_line_item_version', 'mod_id')
    op.drop_column('budget_line_item_version', 'psc_fee_doc_number')
    op.drop_column('budget_line_item_version', 'clin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_line_item_version', sa.Column('clin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item_version', sa.Column('psc_fee_doc_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item_version', sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item_version', sa.Column('proc_shop_fee_percentage', sa.NUMERIC(precision=12, scale=5), autoincrement=False, nullable=True))
    op.add_column('budget_line_item_version', sa.Column('psc_fee_pymt_ref_nbr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item_version', sa.Column('services_component_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('budget_line_item_version', 'budget_line_item_type')
    op.add_column('budget_line_item', sa.Column('clin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item', sa.Column('psc_fee_doc_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item', sa.Column('mod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item', sa.Column('proc_shop_fee_percentage', sa.NUMERIC(precision=12, scale=5), autoincrement=False, nullable=True))
    op.add_column('budget_line_item', sa.Column('psc_fee_pymt_ref_nbr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('budget_line_item', sa.Column('services_component_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('budget_line_item_services_component_id_fkey', 'budget_line_item', 'services_component', ['services_component_id'], ['id'])
    op.create_foreign_key('budget_line_item_clin_id_fkey', 'budget_line_item', 'clin', ['clin_id'], ['id'])
    op.create_foreign_key('budget_line_item_mod_id_fkey', 'budget_line_item', 'agreement_mod', ['mod_id'], ['id'])
    op.drop_column('budget_line_item', 'budget_line_item_type')
    op.drop_table('contract_budget_line_item')
    op.drop_table('iaaa_budget_line_item')
    op.drop_table('grant_budget_line_item')
    op.drop_table('direct_obligation_budget_line_item')
    op.drop_table('grant_budget_line_item_detail')
    op.drop_index(op.f('ix_iaaa_budget_line_item_version_transaction_id'), table_name='iaaa_budget_line_item_version')
    op.drop_index(op.f('ix_iaaa_budget_line_item_version_operation_type'), table_name='iaaa_budget_line_item_version')
    op.drop_index(op.f('ix_iaaa_budget_line_item_version_end_transaction_id'), table_name='iaaa_budget_line_item_version')
    op.drop_table('iaaa_budget_line_item_version')
    op.drop_index(op.f('ix_grant_budget_line_item_version_transaction_id'), table_name='grant_budget_line_item_version')
    op.drop_index(op.f('ix_grant_budget_line_item_version_operation_type'), table_name='grant_budget_line_item_version')
    op.drop_index(op.f('ix_grant_budget_line_item_version_end_transaction_id'), table_name='grant_budget_line_item_version')
    op.drop_table('grant_budget_line_item_version')
    op.drop_index(op.f('ix_grant_budget_line_item_detail_version_transaction_id'), table_name='grant_budget_line_item_detail_version')
    op.drop_index(op.f('ix_grant_budget_line_item_detail_version_operation_type'), table_name='grant_budget_line_item_detail_version')
    op.drop_index(op.f('ix_grant_budget_line_item_detail_version_end_transaction_id'), table_name='grant_budget_line_item_detail_version')
    op.drop_table('grant_budget_line_item_detail_version')
    op.drop_index(op.f('ix_direct_obligation_budget_line_item_version_transaction_id'), table_name='direct_obligation_budget_line_item_version')
    op.drop_index(op.f('ix_direct_obligation_budget_line_item_version_operation_type'), table_name='direct_obligation_budget_line_item_version')
    op.drop_index(op.f('ix_direct_obligation_budget_line_item_version_end_transaction_id'), table_name='direct_obligation_budget_line_item_version')
    op.drop_table('direct_obligation_budget_line_item_version')
    op.drop_index(op.f('ix_contract_budget_line_item_version_transaction_id'), table_name='contract_budget_line_item_version')
    op.drop_index(op.f('ix_contract_budget_line_item_version_operation_type'), table_name='contract_budget_line_item_version')
    op.drop_index(op.f('ix_contract_budget_line_item_version_end_transaction_id'), table_name='contract_budget_line_item_version')
    op.drop_table('contract_budget_line_item_version')
    sa.Enum('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'AS', 'GU', 'MP', 'PR', 'VI', name='statecode').drop(op.get_bind())
    # ### end Alembic commands ###
