"""Agreement id record nullable to account for master budget spreadsheet

Revision ID: 8d8d4eefa1c9
Revises: 920f39962055
Create Date: 2025-09-11 15:35:12.013671+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d8d4eefa1c9'
down_revision: Union[str, None] = '920f39962055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_history', 'agreement_id_record',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement_history', 'agreement_id_record',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
