"""add_temporary_year_end_role

Revision ID: 6d413bd6cd8b
Revises: d11cb8eb36ce
Create Date: 2025-09-03 17:42:54.541719+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6d413bd6cd8b'
down_revision: Union[str, None] = 'd11cb8eb36ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO role (name, permissions)
        SELECT 'TEMPORARY_YEAR_END',
               ARRAY [
                   'GET_AGREEMENT', 'PUT_AGREEMENT', 'PATCH_AGREEMENT', 'POST_AGREEMENT', 'DELETE_AGREEMENT',
                   'GET_BUDGET_LINE_ITEM', 'PUT_BUDGET_LINE_ITEM', 'PATCH_BUDGET_LINE_ITEM', 'POST_BUDGET_LINE_ITEM', 'DELETE_BUDGET_LINE_ITEM',
                   'GET_SERVICES_COMPONENT', 'PUT_SERVICES_COMPONENT', 'PATCH_SERVICES_COMPONENT', 'POST_SERVICES_COMPONENT', 'DELETE_SERVICES_COMPONENT',
                   'GET_BLI_PACKAGE', 'PUT_BLI_PACKAGE', 'PATCH_BLI_PACKAGE', 'POST_BLI_PACKAGE',
                   'GET_CAN', 'PUT_CAN', 'PATCH_CAN', 'POST_CAN', 'DELETE_CAN',
                   'GET_DIVISION',
                   'GET_NOTIFICATION', 'PUT_NOTIFICATION', 'PATCH_NOTIFICATION',
                   'GET_PORTFOLIO', 'PUT_PORTFOLIO', 'PATCH_PORTFOLIO', 'POST_PORTFOLIO',
                   'GET_RESEARCH_PROJECT', 'PUT_RESEARCH_PROJECT', 'POST_RESEARCH_PROJECT',
                   'GET_USER', 'PUT_USER', 'PATCH_USER',
                   'GET_HISTORY',
                   'GET_CHANGE_REQUEST', 'PUT_CHANGE_REQUEST', 'PATCH_CHANGE_REQUEST', 'POST_CHANGE_REQUEST',
                   'GET_UPLOAD_DOCUMENT', 'POST_UPLOAD_DOCUMENT'
               ]::text[]
        WHERE NOT EXISTS (
            SELECT 1 FROM role WHERE name = 'TEMPORARY_YEAR_END'
        );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE name = 'TEMPORARY_YEAR_END'")
    # ### end Alembic commands ###
