"""add indexes for bli API performance optimization

Revision ID: 8baa5cc5d632
Revises: 0fa1f93847f8
Create Date: 2026-02-18 18:22:26.908440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baa5cc5d632'
down_revision: Union[str, None] = '0fa1f93847f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_budget_line_item_date_needed', 'budget_line_item', ['date_needed'], unique=False)
    op.create_index('ix_budget_line_item_status', 'budget_line_item', ['status'], unique=False)
    op.create_index(op.f('ix_change_request_budget_line_item_id'), 'change_request', ['budget_line_item_id'], unique=False)
    op.create_index(op.f('ix_change_request_status'), 'change_request', ['status'], unique=False)
    op.create_index(op.f('ix_change_request_version_budget_line_item_id'), 'change_request_version', ['budget_line_item_id'], unique=False)
    op.create_index(op.f('ix_change_request_version_status'), 'change_request_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_request_version_status'), table_name='change_request_version')
    op.drop_index(op.f('ix_change_request_version_budget_line_item_id'), table_name='change_request_version')
    op.drop_index(op.f('ix_change_request_status'), table_name='change_request')
    op.drop_index(op.f('ix_change_request_budget_line_item_id'), table_name='change_request')
    op.drop_index('ix_budget_line_item_status', table_name='budget_line_item')
    op.drop_index('ix_budget_line_item_date_needed', table_name='budget_line_item')
    # ### end Alembic commands ###
