"""remove current procurement tracker model (will add new model design)

Revision ID: 4ca028da2a69
Revises: da5d9205b20e
Create Date: 2026-01-14 18:23:33.094272+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca028da2a69'
down_revision: Union[str, None] = 'da5d9205b20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop child tables first (those with foreign keys to procurement_step)
    op.drop_table('procurement_award')
    op.drop_table('procurement_acquisition_planning')
    op.drop_table('procurement_pre_solicitation')
    op.drop_table('procurement_solicitation')
    op.drop_table('procurement_preaward')
    op.drop_table('procurement_evaluation')

    # Break circular dependency: drop FK from procurement_tracker to procurement_step
    op.drop_constraint('fk_procurement_tracker_procurement_step', 'procurement_tracker', type_='foreignkey')

    # Now drop procurement_step (still has FK to procurement_tracker, but that's ok)
    op.drop_table('procurement_step')

    # Finally drop procurement_tracker
    op.drop_table('procurement_tracker')

    # Drop version tables and indexes
    op.drop_index(op.f('ix_procurement_solicitation_version_end_transaction_id'), table_name='procurement_solicitation_version')
    op.drop_index(op.f('ix_procurement_solicitation_version_operation_type'), table_name='procurement_solicitation_version')
    op.drop_index(op.f('ix_procurement_solicitation_version_transaction_id'), table_name='procurement_solicitation_version')
    op.drop_table('procurement_solicitation_version')
    op.drop_index(op.f('ix_procurement_pre_solicitation_version_end_transaction_id'), table_name='procurement_pre_solicitation_version')
    op.drop_index(op.f('ix_procurement_pre_solicitation_version_operation_type'), table_name='procurement_pre_solicitation_version')
    op.drop_index(op.f('ix_procurement_pre_solicitation_version_transaction_id'), table_name='procurement_pre_solicitation_version')
    op.drop_table('procurement_pre_solicitation_version')
    op.drop_index(op.f('ix_procurement_acquisition_planning_version_end_transaction_id'), table_name='procurement_acquisition_planning_version')
    op.drop_index(op.f('ix_procurement_acquisition_planning_version_operation_type'), table_name='procurement_acquisition_planning_version')
    op.drop_index(op.f('ix_procurement_acquisition_planning_version_transaction_id'), table_name='procurement_acquisition_planning_version')
    op.drop_table('procurement_acquisition_planning_version')
    op.drop_index(op.f('ix_procurement_preaward_version_end_transaction_id'), table_name='procurement_preaward_version')
    op.drop_index(op.f('ix_procurement_preaward_version_operation_type'), table_name='procurement_preaward_version')
    op.drop_index(op.f('ix_procurement_preaward_version_transaction_id'), table_name='procurement_preaward_version')
    op.drop_table('procurement_preaward_version')
    op.drop_index(op.f('ix_procurement_award_version_end_transaction_id'), table_name='procurement_award_version')
    op.drop_index(op.f('ix_procurement_award_version_operation_type'), table_name='procurement_award_version')
    op.drop_index(op.f('ix_procurement_award_version_transaction_id'), table_name='procurement_award_version')
    op.drop_table('procurement_award_version')
    op.drop_index(op.f('ix_procurement_evaluation_version_end_transaction_id'), table_name='procurement_evaluation_version')
    op.drop_index(op.f('ix_procurement_evaluation_version_operation_type'), table_name='procurement_evaluation_version')
    op.drop_index(op.f('ix_procurement_evaluation_version_transaction_id'), table_name='procurement_evaluation_version')
    op.drop_table('procurement_evaluation_version')
    op.drop_index(op.f('ix_procurement_tracker_version_end_transaction_id'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_operation_type'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_transaction_id'), table_name='procurement_tracker_version')
    op.drop_table('procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_step_version_end_transaction_id'), table_name='procurement_step_version')
    op.drop_index(op.f('ix_procurement_step_version_operation_type'), table_name='procurement_step_version')
    op.drop_index(op.f('ix_procurement_step_version_transaction_id'), table_name='procurement_step_version')
    op.drop_table('procurement_step_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_step_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('procurement_tracker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_step_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_step_version_transaction_id'), 'procurement_step_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_step_version_operation_type'), 'procurement_step_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_step_version_end_transaction_id'), 'procurement_step_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_tracker_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_tracker_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_tracker_version_transaction_id'), 'procurement_tracker_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_operation_type'), 'procurement_tracker_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_end_transaction_id'), 'procurement_tracker_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_evaluation_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_evaluation_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_evaluation_version_transaction_id'), 'procurement_evaluation_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_evaluation_version_operation_type'), 'procurement_evaluation_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_evaluation_version_end_transaction_id'), 'procurement_evaluation_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_award_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('financial_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_award_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_award_version_transaction_id'), 'procurement_award_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_award_version_operation_type'), 'procurement_award_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_award_version_end_transaction_id'), 'procurement_award_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_preaward_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_preaward_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_preaward_version_transaction_id'), 'procurement_preaward_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_preaward_version_operation_type'), 'procurement_preaward_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_preaward_version_end_transaction_id'), 'procurement_preaward_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_evaluation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_evaluation_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_evaluation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_evaluation_pkey'))
    )
    op.create_table('procurement_preaward',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_preaward_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_preaward_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_preaward_pkey'))
    )
    op.create_table('procurement_step',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('procurement_step_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('procurement_tracker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], name='procurement_step_agreement_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], name='procurement_step_created_by_fkey'),
    sa.ForeignKeyConstraint(['procurement_tracker_id'], ['procurement_tracker.id'], name='procurement_step_procurement_tracker_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], name='procurement_step_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='procurement_step_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('procurement_acquisition_planning_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_acquisition_planning_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_acquisition_planning_version_transaction_id'), 'procurement_acquisition_planning_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_acquisition_planning_version_operation_type'), 'procurement_acquisition_planning_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_acquisition_planning_version_end_transaction_id'), 'procurement_acquisition_planning_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_pre_solicitation_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_pre_solicitation_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_pre_solicitation_version_transaction_id'), 'procurement_pre_solicitation_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_pre_solicitation_version_operation_type'), 'procurement_pre_solicitation_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_pre_solicitation_version_end_transaction_id'), 'procurement_pre_solicitation_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_solicitation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_solicitation_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_solicitation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_solicitation_pkey'))
    )
    op.create_table('procurement_tracker',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('procurement_tracker_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], name='procurement_tracker_agreement_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], name='procurement_tracker_created_by_fkey'),
    sa.ForeignKeyConstraint(['current_step_id'], ['procurement_step.id'], name='fk_procurement_tracker_procurement_step'),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], name='procurement_tracker_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='procurement_tracker_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('procurement_solicitation_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('procurement_solicitation_version_pkey'))
    )
    op.create_index(op.f('ix_procurement_solicitation_version_transaction_id'), 'procurement_solicitation_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_solicitation_version_operation_type'), 'procurement_solicitation_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_solicitation_version_end_transaction_id'), 'procurement_solicitation_version', ['end_transaction_id'], unique=False)
    op.create_table('procurement_pre_solicitation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_pre_solicitation_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_pre_solicitation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_pre_solicitation_pkey'))
    )
    op.create_table('procurement_acquisition_planning',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_acquisition_planning_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_acquisition_planning_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_acquisition_planning_pkey'))
    )
    op.create_table('procurement_award',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('financial_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['ops_user.id'], name=op.f('procurement_award_completed_by_fkey')),
    sa.ForeignKeyConstraint(['id'], ['procurement_step.id'], name=op.f('procurement_award_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_award_pkey'))
    )
    # ### end Alembic commands ###
