"""add user_session and notification indices

Revision ID: da5d9205b20e
Revises: 08af75126345
Create Date: 2026-01-08 19:13:11.698409+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5d9205b20e'
down_revision: Union[str, None] = '08af75126345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_change_request_agreement_id'), 'change_request', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_change_request_change_request_type'), 'change_request', ['change_request_type'], unique=False)
    op.create_index(op.f('ix_change_request_version_agreement_id'), 'change_request_version', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_change_request_version_change_request_type'), 'change_request_version', ['change_request_type'], unique=False)
    op.create_index('idx_notification_complete', 'notification', ['is_read', 'notification_type', sa.literal_column('created_on DESC')], unique=False)
    op.create_index('idx_notification_recipient_created', 'notification', ['recipient_id', sa.literal_column('created_on DESC')], unique=False)
    op.create_index(op.f('ix_notification_change_request_id'), 'notification', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_notification_type'), 'notification', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_version_change_request_id'), 'notification_version', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_notification_version_is_read'), 'notification_version', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_version_notification_type'), 'notification_version', ['notification_type'], unique=False)
    op.create_index('ix_user_session_user_id_created_on', 'user_session', ['user_id', 'created_on'], unique=False)
    op.create_index('ix_user_session_user_id_is_active', 'user_session', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_session_user_id_is_active', table_name='user_session')
    op.drop_index('ix_user_session_user_id_created_on', table_name='user_session')
    op.drop_index(op.f('ix_notification_version_notification_type'), table_name='notification_version')
    op.drop_index(op.f('ix_notification_version_is_read'), table_name='notification_version')
    op.drop_index(op.f('ix_notification_version_change_request_id'), table_name='notification_version')
    op.drop_index(op.f('ix_notification_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_change_request_id'), table_name='notification')
    op.drop_index('idx_notification_recipient_created', table_name='notification')
    op.drop_index('idx_notification_complete', table_name='notification')
    op.drop_index(op.f('ix_change_request_version_change_request_type'), table_name='change_request_version')
    op.drop_index(op.f('ix_change_request_version_agreement_id'), table_name='change_request_version')
    op.drop_index(op.f('ix_change_request_change_request_type'), table_name='change_request')
    op.drop_index(op.f('ix_change_request_agreement_id'), table_name='change_request')
    # ### end Alembic commands ###
