"""Add update procurement tracker step

Revision ID: aa18dcfe74a5
Revises: e67974a317f6
Create Date: 2026-01-29 20:30:45.828145+00:00

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "aa18dcfe74a5"
down_revision: Union[str, None] = "e67974a317f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="ops",
        enum_name="opseventtype",
        new_values=[
            "CREATE_BLI",
            "UPDATE_BLI",
            "DELETE_BLI",
            "SEND_BLI_FOR_APPROVAL",
            "CREATE_PROJECT",
            "GET_AGREEMENT",
            "CREATE_NEW_AGREEMENT",
            "UPDATE_AGREEMENT",
            "DELETE_AGREEMENT",
            "CREATE_NEW_CAN",
            "UPDATE_CAN",
            "DELETE_CAN",
            "CREATE_CAN_FUNDING_RECEIVED",
            "UPDATE_CAN_FUNDING_RECEIVED",
            "DELETE_CAN_FUNDING_RECEIVED",
            "CREATE_CAN_FUNDING_BUDGET",
            "UPDATE_CAN_FUNDING_BUDGET",
            "DELETE_CAN_FUNDING_BUDGET",
            "CREATE_CAN_FUNDING_DETAILS",
            "UPDATE_CAN_FUNDING_DETAILS",
            "DELETE_CAN_FUNDING_DETAILS",
            "ACKNOWLEDGE_NOTIFICATION",
            "CREATE_BLI_PACKAGE",
            "UPDATE_BLI_PACKAGE",
            "CREATE_SERVICES_COMPONENT",
            "UPDATE_SERVICES_COMPONENT",
            "DELETE_SERVICES_COMPONENT",
            "CREATE_PROCUREMENT_ACQUISITION_PLANNING",
            "UPDATE_PROCUREMENT_ACQUISITION_PLANNING",
            "DELETE_PROCUREMENT_ACQUISITION_PLANNING",
            "UPDATE_PROCUREMENT_TRACKER_STEP",
            "CREATE_DOCUMENT",
            "UPDATE_DOCUMENT",
            "LOGIN_ATTEMPT",
            "LOGOUT",
            "IDLE_LOGOUT",
            "GET_USER_DETAILS",
            "CREATE_USER",
            "UPDATE_USER",
            "DEACTIVATE_USER",
            "CREATE_PORTFOLIO_URL",
            "UPDATE_PORTFOLIO_URL",
            "DELETE_PORTFOLIO_URL",
            "CREATE_CHANGE_REQUEST",
            "UPDATE_CHANGE_REQUEST",
            "DELETE_CHANGE_REQUEST",
            "CREATE_PROCUREMENT_SHOP",
            "UPDATE_PROCUREMENT_SHOP",
            "DELETE_PROCUREMENT_SHOP",
            "CREATE_ROLE",
            "UPDATE_ROLE",
            "DELETE_ROLE",
            "CREATE_USER_SESSION",
            "UPDATE_USER_SESSION",
            "DELETE_USER_SESSION",
        ],
        affected_columns=[
            TableReference(table_schema="ops", table_name="ops_event", column_name="event_type"),
            TableReference(table_schema="ops", table_name="ops_event_version", column_name="event_type"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="ops",
        enum_name="opseventtype",
        new_values=[
            "CREATE_BLI",
            "UPDATE_BLI",
            "DELETE_BLI",
            "SEND_BLI_FOR_APPROVAL",
            "CREATE_PROJECT",
            "GET_AGREEMENT",
            "CREATE_NEW_AGREEMENT",
            "UPDATE_AGREEMENT",
            "DELETE_AGREEMENT",
            "CREATE_NEW_CAN",
            "UPDATE_CAN",
            "DELETE_CAN",
            "CREATE_CAN_FUNDING_RECEIVED",
            "UPDATE_CAN_FUNDING_RECEIVED",
            "DELETE_CAN_FUNDING_RECEIVED",
            "CREATE_CAN_FUNDING_BUDGET",
            "UPDATE_CAN_FUNDING_BUDGET",
            "DELETE_CAN_FUNDING_BUDGET",
            "CREATE_CAN_FUNDING_DETAILS",
            "UPDATE_CAN_FUNDING_DETAILS",
            "DELETE_CAN_FUNDING_DETAILS",
            "ACKNOWLEDGE_NOTIFICATION",
            "CREATE_BLI_PACKAGE",
            "UPDATE_BLI_PACKAGE",
            "CREATE_SERVICES_COMPONENT",
            "UPDATE_SERVICES_COMPONENT",
            "DELETE_SERVICES_COMPONENT",
            "CREATE_PROCUREMENT_ACQUISITION_PLANNING",
            "UPDATE_PROCUREMENT_ACQUISITION_PLANNING",
            "DELETE_PROCUREMENT_ACQUISITION_PLANNING",
            "CREATE_DOCUMENT",
            "UPDATE_DOCUMENT",
            "LOGIN_ATTEMPT",
            "LOGOUT",
            "IDLE_LOGOUT",
            "GET_USER_DETAILS",
            "CREATE_USER",
            "UPDATE_USER",
            "DEACTIVATE_USER",
            "CREATE_PORTFOLIO_URL",
            "UPDATE_PORTFOLIO_URL",
            "DELETE_PORTFOLIO_URL",
            "CREATE_CHANGE_REQUEST",
            "UPDATE_CHANGE_REQUEST",
            "DELETE_CHANGE_REQUEST",
            "CREATE_PROCUREMENT_SHOP",
            "UPDATE_PROCUREMENT_SHOP",
            "DELETE_PROCUREMENT_SHOP",
            "CREATE_ROLE",
            "UPDATE_ROLE",
            "DELETE_ROLE",
            "CREATE_USER_SESSION",
            "UPDATE_USER_SESSION",
            "DELETE_USER_SESSION",
        ],
        affected_columns=[
            TableReference(table_schema="ops", table_name="ops_event", column_name="event_type"),
            TableReference(table_schema="ops", table_name="ops_event_version", column_name="event_type"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
