"""Add pre_award approval response fields to procurement tracker step

Revision ID: d6e7f8a9b0c1
Revises: c9a1b2d3e4f5
Create Date: 2026-03-23 16:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e7f8a9b0c1'
down_revision: Union[str, None] = 'c9a1b2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_status', sa.String(length=20), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_responded_by', sa.Integer(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_responded_date', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_reviewer_notes', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_pre_award_responded_by',
        'procurement_tracker_step', 'ops_user',
        ['pre_award_approval_responded_by'], ['id']
    )
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_status', sa.String(length=20), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_responded_by', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_responded_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_reviewer_notes', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_reviewer_notes')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_responded_date')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_responded_by')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_status')
    op.drop_constraint('fk_pre_award_responded_by', 'procurement_tracker_step', type_='foreignkey')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_reviewer_notes')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_responded_date')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_responded_by')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_status')
    # ### end Alembic commands ###
