"""add notification indexes

Revision ID: deb9c01d49f7
Revises: 08af75126345
Create Date: 2026-01-08 15:26:14.574476+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb9c01d49f7'
down_revision: Union[str, None] = '08af75126345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_change_request_agreement_id'), 'change_request', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_change_request_version_agreement_id'), 'change_request_version', ['agreement_id'], unique=False)
    op.create_index('idx_notification_recipient_created', 'notification', ['recipient_id', 'created_on'], unique=False, postgresql_ops={'created_on': 'DESC'})
    op.create_index(op.f('ix_notification_change_request_id'), 'notification', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_version_change_request_id'), 'notification_version', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_notification_version_is_read'), 'notification_version', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_version_is_read'), table_name='notification_version')
    op.drop_index(op.f('ix_notification_version_change_request_id'), table_name='notification_version')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_change_request_id'), table_name='notification')
    op.drop_index('idx_notification_recipient_created', table_name='notification', postgresql_ops={'created_on': 'DESC'})
    op.drop_index(op.f('ix_change_request_version_agreement_id'), table_name='change_request_version')
    op.drop_index(op.f('ix_change_request_agreement_id'), table_name='change_request')
    # ### end Alembic commands ###
