"""Condensing projects into single table

Revision ID: 023fbc1e5eb3
Revises: ae2ee26e19d5
Create Date: 2026-04-21 21:32:21.681847+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "023fbc1e5eb3"
down_revision: Union[str, None] = "ae2ee26e19d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new tables
    op.add_column("project", sa.Column("origination_date", sa.Date(), nullable=True))
    op.add_column("project_version", sa.Column("origination_date", sa.Date(), autoincrement=False, nullable=True))

    # Transfer data from old tables to new rows
    conn = op.get_bind()
    research_projects = conn.execute(sa.text("SELECT id, origination_date FROM research_project")).fetchall()
    for project_id, origination_date in research_projects:
        if origination_date is not None:
            conn.execute(
                sa.text("UPDATE project SET origination_date = :date WHERE id = :id"),
                {"date": origination_date, "id": project_id},
            )

    # Drop old tables and indices
    op.drop_index(op.f("ix_research_project_version_end_transaction_id"), table_name="research_project_version")
    op.drop_index(op.f("ix_research_project_version_operation_type"), table_name="research_project_version")
    op.drop_index(op.f("ix_research_project_version_transaction_id"), table_name="research_project_version")
    op.drop_table("research_project_version")
    op.drop_table("administrative_and_support_project")
    op.drop_index(
        op.f("ix_administrative_and_support_project_version_end_trans_a4ec"),
        table_name="administrative_and_support_project_version",
    )
    op.drop_index(
        op.f("ix_administrative_and_support_project_version_operation_type"),
        table_name="administrative_and_support_project_version",
    )
    op.drop_index(
        op.f("ix_administrative_and_support_project_version_transaction_id"),
        table_name="administrative_and_support_project_version",
    )
    op.drop_table("administrative_and_support_project_version")
    op.drop_table("research_project")
    op.drop_index(op.f("idx_notification_procurement_tracker_step"), table_name="notification")
    op.create_index(
        op.f("ix_notification_version_procurement_tracker_step_id"),
        "notification_version",
        ["procurement_tracker_step_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate Table
    op.create_table(
        "research_project",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("origination_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["id"], ["project.id"], name=op.f("research_project_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("research_project_pkey")),
    )
    op.create_table(
        "administrative_and_support_project_version",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("administrative_and_support_project_version_pkey")),
    )
    op.create_index(
        op.f("ix_administrative_and_support_project_version_transaction_id"),
        "administrative_and_support_project_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_administrative_and_support_project_version_operation_type"),
        "administrative_and_support_project_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_administrative_and_support_project_version_end_trans_a4ec"),
        "administrative_and_support_project_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "administrative_and_support_project",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["id"], ["project.id"], name=op.f("administrative_and_support_project_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("administrative_and_support_project_pkey")),
    )
    op.create_table(
        "research_project_version",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("origination_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("research_project_version_pkey")),
    )
    op.create_index(
        op.f("ix_research_project_version_transaction_id"), "research_project_version", ["transaction_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_project_version_operation_type"), "research_project_version", ["operation_type"], unique=False
    )
    op.create_index(
        op.f("ix_research_project_version_end_transaction_id"),
        "research_project_version",
        ["end_transaction_id"],
        unique=False,
    )

    # Transfer data back to old tables
    conn = op.get_bind()
    research_projects = conn.execute(
        sa.text("SELECT id, origination_date FROM project WHERE project_type = 'RESEARCH'")
    ).fetchall()
    for project_id, origination_date in research_projects:
        conn.execute(
            sa.text("INSERT INTO research_project (id, origination_date) VALUES (:id, :date)"),
            {"id": project_id, "date": origination_date},
        )

    administrative_projects = conn.execute(
        sa.text("SELECT id FROM project WHERE project_type = 'ADMINISTRATIVE_AND_SUPPORT'")
    ).fetchall()
    for (project_id,) in administrative_projects:
        conn.execute(sa.text("INSERT INTO administrative_and_support_project (id) VALUES (:id)"), {"id": project_id})

    op.drop_column("project_version", "origination_date")
    op.drop_column("project", "origination_date")
    op.drop_index(op.f("ix_notification_version_procurement_tracker_step_id"), table_name="notification_version")
    op.create_index(
        op.f("idx_notification_procurement_tracker_step"),
        "notification",
        ["procurement_tracker_step_id", "is_read"],
        unique=False,
    )

    # ### end Alembic commands ###
