"""Add procurement tracker models with separate steps table

Revision ID: ab8aeac6870e
Revises: 4ca028da2a69
Create Date: 2026-01-16 01:31:03.801041+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab8aeac6870e'
down_revision: Union[str, None] = '4ca028da2a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='procurementtrackerstepstatus').create(op.get_bind())
    sa.Enum('ACQUISITION_PLANNING', 'PRE_SOLICITATION', 'SOLICITATION', 'EVALUATION', 'PRE_AWARD', 'AWARD', name='procurementtrackersteptype').create(op.get_bind())
    sa.Enum('DEFAULT', name='procurementtrackertype').create(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', 'COMPLETED', name='procurementtrackerstatus').create(op.get_bind())
    op.create_table('default_procurement_tracker_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_default_procurement_tracker_version_end_transaction_id'), 'default_procurement_tracker_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_default_procurement_tracker_version_operation_type'), 'default_procurement_tracker_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_default_procurement_tracker_version_transaction_id'), 'default_procurement_tracker_version', ['transaction_id'], unique=False)
    op.create_table('procurement_tracker_step_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('procurement_tracker_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('step_type', postgresql.ENUM('ACQUISITION_PLANNING', 'PRE_SOLICITATION', 'SOLICITATION', 'EVALUATION', 'PRE_AWARD', 'AWARD', name='procurementtrackersteptype', create_type=False), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='procurementtrackerstepstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('step_start_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('step_completed_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('acquisition_planning_task_completed_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('acquisition_planning_date_completed', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('acquisition_planning_notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_procurement_tracker_step_version_end_transaction_id'), 'procurement_tracker_step_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_step_version_operation_type'), 'procurement_tracker_step_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_step_version_transaction_id'), 'procurement_tracker_step_version', ['transaction_id'], unique=False)
    op.create_table('procurement_tracker_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('agreement_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'COMPLETED', name='procurementtrackerstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('procurement_action', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tracker_type', postgresql.ENUM('DEFAULT', name='procurementtrackertype', create_type=False), autoincrement=False, nullable=True),
    sa.Column('active_step_number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_procurement_tracker_version_end_transaction_id'), 'procurement_tracker_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_operation_type'), 'procurement_tracker_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_transaction_id'), 'procurement_tracker_version', ['transaction_id'], unique=False)
    op.create_table('procurement_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'COMPLETED', name='procurementtrackerstatus', create_type=False), nullable=False),
    sa.Column('procurement_action', sa.Integer(), nullable=True),
    sa.Column('tracker_type', postgresql.ENUM('DEFAULT', name='procurementtrackertype', create_type=False), nullable=False),
    sa.Column('active_step_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreement.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['procurement_action'], ['procurement_action.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_procurement_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['procurement_tracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_tracker_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procurement_tracker_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_type', postgresql.ENUM('ACQUISITION_PLANNING', 'PRE_SOLICITATION', 'SOLICITATION', 'EVALUATION', 'PRE_AWARD', 'AWARD', name='procurementtrackersteptype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='procurementtrackerstepstatus', create_type=False), nullable=False),
    sa.Column('step_start_date', sa.Date(), nullable=True),
    sa.Column('step_completed_date', sa.Date(), nullable=True),
    sa.Column('acquisition_planning_task_completed_by', sa.Integer(), nullable=True),
    sa.Column('acquisition_planning_date_completed', sa.Date(), nullable=True),
    sa.Column('acquisition_planning_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_planning_task_completed_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['ops_user.id'], ),
    sa.ForeignKeyConstraint(['procurement_tracker_id'], ['procurement_tracker.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['ops_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procurement_tracker_step')
    op.drop_table('default_procurement_tracker')
    op.drop_table('procurement_tracker')
    op.drop_index(op.f('ix_procurement_tracker_version_transaction_id'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_operation_type'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_end_transaction_id'), table_name='procurement_tracker_version')
    op.drop_table('procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_step_version_transaction_id'), table_name='procurement_tracker_step_version')
    op.drop_index(op.f('ix_procurement_tracker_step_version_operation_type'), table_name='procurement_tracker_step_version')
    op.drop_index(op.f('ix_procurement_tracker_step_version_end_transaction_id'), table_name='procurement_tracker_step_version')
    op.drop_table('procurement_tracker_step_version')
    op.drop_index(op.f('ix_default_procurement_tracker_version_transaction_id'), table_name='default_procurement_tracker_version')
    op.drop_index(op.f('ix_default_procurement_tracker_version_operation_type'), table_name='default_procurement_tracker_version')
    op.drop_index(op.f('ix_default_procurement_tracker_version_end_transaction_id'), table_name='default_procurement_tracker_version')
    op.drop_table('default_procurement_tracker_version')
    sa.Enum('ACTIVE', 'INACTIVE', 'COMPLETED', name='procurementtrackerstatus').drop(op.get_bind())
    sa.Enum('DEFAULT', name='procurementtrackertype').drop(op.get_bind())
    sa.Enum('ACQUISITION_PLANNING', 'PRE_SOLICITATION', 'SOLICITATION', 'EVALUATION', 'PRE_AWARD', 'AWARD', name='procurementtrackersteptype').drop(op.get_bind())
    sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'SKIPPED', name='procurementtrackerstepstatus').drop(op.get_bind())
    # ### end Alembic commands ###
