"""add indexes for projects API performance optimization

Revision ID: a34ae6c533ad
Revises: f31febdbe055
Create Date: 2026-02-16 15:16:34.205126+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34ae6c533ad'
down_revision: Union[str, None] = 'f31febdbe055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agreement_project_id', 'agreement', ['project_id'], unique=False)
    op.create_index('ix_budget_line_item_agreement_id', 'budget_line_item', ['agreement_id'], unique=False)
    op.create_index('ix_budget_line_item_can_id', 'budget_line_item', ['can_id'], unique=False)
    op.create_index('ix_can_funding_details_id', 'can', ['funding_details_id'], unique=False)
    op.create_index('ix_can_portfolio_id', 'can', ['portfolio_id'], unique=False)
    op.create_index('ix_project_title_pattern', 'project', ['title'], unique=False, postgresql_ops={'title': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_title_pattern', table_name='project', postgresql_ops={'title': 'text_pattern_ops'})
    op.drop_index('ix_can_portfolio_id', table_name='can')
    op.drop_index('ix_can_funding_details_id', table_name='can')
    op.drop_index('ix_budget_line_item_can_id', table_name='budget_line_item')
    op.drop_index('ix_budget_line_item_agreement_id', table_name='budget_line_item')
    op.drop_index('ix_agreement_project_id', table_name='agreement')
    # ### end Alembic commands ###
