"""Add pre_award fields to procurement tracker step

Revision ID: a5a4926761c6
Revises: 7c7efdb9d2da
Create Date: 2026-03-12 19:48:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a4926761c6'
down_revision: Union[str, None] = '7c7efdb9d2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_tracker_step', sa.Column('pre_award_target_completion_date', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_task_completed_by', sa.Integer(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_date_completed', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'procurement_tracker_step', 'ops_user', ['pre_award_task_completed_by'], ['id'])
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_target_completion_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_task_completed_by', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_date_completed', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_notes', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_tracker_step_version', 'pre_award_notes')
    op.drop_column('procurement_tracker_step_version', 'pre_award_date_completed')
    op.drop_column('procurement_tracker_step_version', 'pre_award_task_completed_by')
    op.drop_column('procurement_tracker_step_version', 'pre_award_target_completion_date')
    op.drop_constraint(None, 'procurement_tracker_step', type_='foreignkey')
    op.drop_column('procurement_tracker_step', 'pre_award_notes')
    op.drop_column('procurement_tracker_step', 'pre_award_date_completed')
    op.drop_column('procurement_tracker_step', 'pre_award_task_completed_by')
    op.drop_column('procurement_tracker_step', 'pre_award_target_completion_date')
    # ### end Alembic commands ###
