"""Add pre_award approval request fields to procurement tracker step

Revision ID: b5f3e9a8c4d1
Revises: a3b4c5d6e7f8
Create Date: 2026-03-16 17:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f3e9a8c4d1'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_requested', sa.Boolean(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_requested_date', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_approval_requested_by', sa.Integer(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('pre_award_requestor_notes', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_pre_award_requested_by',
        'procurement_tracker_step', 'ops_user',
        ['pre_award_approval_requested_by'], ['id']
    )
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_requested', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_requested_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_approval_requested_by', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('pre_award_requestor_notes', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_tracker_step_version', 'pre_award_requestor_notes')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_requested_by')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_requested_date')
    op.drop_column('procurement_tracker_step_version', 'pre_award_approval_requested')
    op.drop_constraint('fk_pre_award_requested_by', 'procurement_tracker_step', type_='foreignkey')
    op.drop_column('procurement_tracker_step', 'pre_award_requestor_notes')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_requested_by')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_requested_date')
    op.drop_column('procurement_tracker_step', 'pre_award_approval_requested')
    # ### end Alembic commands ###
