"""Add grant number agreement history types

Revision ID: a7c3f1e9b2d4
Revises: f2a3b4c5d6e7
Create Date: 2026-07-27 12:00:00.000000+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "a7c3f1e9b2d4"
down_revision: Union[str, None] = "f2a3b4c5d6e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="ops",
        enum_name="agreementhistorytype",
        new_values=[
            "AGREEMENT_CREATED",
            "AGREEMENT_UPDATED",
            "AGREEMENT_DELETED",
            "BUDGET_LINE_ITEM_CREATED",
            "BUDGET_LINE_ITEM_UPDATED",
            "BUDGET_LINE_ITEM_DELETED",
            "CHANGE_REQUEST_CREATED",
            "CHANGE_REQUEST_UPDATED",
            "CHANGE_REQUEST_DELETED",
            "PROCUREMENT_SHOP_UPDATED",
            "PROCUREMENT_TRACKER_STEP_UPDATED",
            "SERVICE_COMPONENT_CREATED",
            "SERVICE_COMPONENT_UPDATED",
            "SERVICE_COMPONENT_DELETED",
            "GRANT_NUMBER_CREATED",
            "GRANT_NUMBER_UPDATED",
            "GRANT_NUMBER_DELETED",
        ],
        affected_columns=[
            TableReference(table_schema="ops", table_name="agreement_history", column_name="history_type"),
            TableReference(table_schema="ops", table_name="agreement_history_version", column_name="history_type"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="ops",
        enum_name="agreementhistorytype",
        new_values=[
            "AGREEMENT_CREATED",
            "AGREEMENT_UPDATED",
            "AGREEMENT_DELETED",
            "BUDGET_LINE_ITEM_CREATED",
            "BUDGET_LINE_ITEM_UPDATED",
            "BUDGET_LINE_ITEM_DELETED",
            "CHANGE_REQUEST_CREATED",
            "CHANGE_REQUEST_UPDATED",
            "CHANGE_REQUEST_DELETED",
            "PROCUREMENT_SHOP_UPDATED",
            "PROCUREMENT_TRACKER_STEP_UPDATED",
            "SERVICE_COMPONENT_CREATED",
            "SERVICE_COMPONENT_UPDATED",
            "SERVICE_COMPONENT_DELETED",
        ],
        affected_columns=[
            TableReference(table_schema="ops", table_name="agreement_history", column_name="history_type"),
            TableReference(table_schema="ops", table_name="agreement_history_version", column_name="history_type"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
