"""add step two model for procurement tracker

Revision ID: 33fad4b15baa
Revises: f31febdbe055
Create Date: 2026-02-04 18:47:28.692681+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33fad4b15baa"
down_revision: Union[str, None] = "f31febdbe055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "procurement_tracker_step", sa.Column("pre_solicitation_target_completion_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "procurement_tracker_step", sa.Column("pre_solicitation_task_completed_by", sa.Integer(), nullable=True)
    )
    op.add_column("procurement_tracker_step", sa.Column("pre_solicitation_date_completed", sa.Date(), nullable=True))
    op.add_column("procurement_tracker_step", sa.Column("pre_solicitation_notes", sa.Text(), nullable=True))
    op.add_column(
        "procurement_tracker_step", sa.Column("pre_solicitation_draft_solicitation_date", sa.Date(), nullable=True)
    )
    op.create_foreign_key(None, "procurement_tracker_step", "ops_user", ["pre_solicitation_task_completed_by"], ["id"])
    op.add_column(
        "procurement_tracker_step_version",
        sa.Column("pre_solicitation_target_completion_date", sa.Date(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "procurement_tracker_step_version",
        sa.Column("pre_solicitation_task_completed_by", sa.Integer(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "procurement_tracker_step_version",
        sa.Column("pre_solicitation_date_completed", sa.Date(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "procurement_tracker_step_version",
        sa.Column("pre_solicitation_notes", sa.Text(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "procurement_tracker_step_version",
        sa.Column("pre_solicitation_draft_solicitation_date", sa.Date(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("procurement_tracker_step_version", "pre_solicitation_draft_solicitation_date")
    op.drop_column("procurement_tracker_step_version", "pre_solicitation_notes")
    op.drop_column("procurement_tracker_step_version", "pre_solicitation_date_completed")
    op.drop_column("procurement_tracker_step_version", "pre_solicitation_task_completed_by")
    op.drop_column("procurement_tracker_step_version", "pre_solicitation_target_completion_date")
    op.drop_constraint(None, "procurement_tracker_step", type_="foreignkey")
    op.drop_column("procurement_tracker_step", "pre_solicitation_draft_solicitation_date")
    op.drop_column("procurement_tracker_step", "pre_solicitation_notes")
    op.drop_column("procurement_tracker_step", "pre_solicitation_date_completed")
    op.drop_column("procurement_tracker_step", "pre_solicitation_task_completed_by")
    op.drop_column("procurement_tracker_step", "pre_solicitation_target_completion_date")
    # ### end Alembic commands ###
