"""Adding solicitation step data to procurement tracker model

Revision ID: b820f4653e83
Revises: 0fa1f93847f8
Create Date: 2026-02-20 16:02:50.514634+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b820f4653e83'
down_revision: Union[str, None] = '0fa1f93847f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_tracker_step', sa.Column('solicitation_task_completed_by', sa.Integer(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('solicitation_date_completed', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('solicitation_notes', sa.Text(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('solicitation_period_start_date', sa.Date(), nullable=True))
    op.add_column('procurement_tracker_step', sa.Column('solicitation_period_end_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'procurement_tracker_step', 'ops_user', ['solicitation_task_completed_by'], ['id'])
    op.add_column('procurement_tracker_step_version', sa.Column('solicitation_task_completed_by', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('solicitation_date_completed', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('solicitation_notes', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('solicitation_period_start_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('procurement_tracker_step_version', sa.Column('solicitation_period_end_date', sa.Date(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_tracker_step_version', 'solicitation_period_end_date')
    op.drop_column('procurement_tracker_step_version', 'solicitation_period_start_date')
    op.drop_column('procurement_tracker_step_version', 'solicitation_notes')
    op.drop_column('procurement_tracker_step_version', 'solicitation_date_completed')
    op.drop_column('procurement_tracker_step_version', 'solicitation_task_completed_by')
    op.drop_constraint(None, 'procurement_tracker_step', type_='foreignkey')
    op.drop_column('procurement_tracker_step', 'solicitation_period_end_date')
    op.drop_column('procurement_tracker_step', 'solicitation_period_start_date')
    op.drop_column('procurement_tracker_step', 'solicitation_notes')
    op.drop_column('procurement_tracker_step', 'solicitation_date_completed')
    op.drop_column('procurement_tracker_step', 'solicitation_task_completed_by')
    # ### end Alembic commands ###
