"""add indices to procurement tracker models

Revision ID: e67974a317f6
Revises: 898aa0aa9343
Create Date: 2026-01-27 15:26:58.842801+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67974a317f6'
down_revision: Union[str, None] = '898aa0aa9343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_procurement_action_agreement_id'), 'procurement_action', ['agreement_id'], unique=False)
    op.create_index('ix_procurement_action_agreement_id_award_type_status', 'procurement_action', ['agreement_id', 'award_type', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_action_award_type'), 'procurement_action', ['award_type'], unique=False)
    op.create_index(op.f('ix_procurement_action_status'), 'procurement_action', ['status'], unique=False)
    op.create_index(op.f('ix_procurement_action_version_agreement_id'), 'procurement_action_version', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_procurement_action_version_award_type'), 'procurement_action_version', ['award_type'], unique=False)
    op.create_index(op.f('ix_procurement_action_version_status'), 'procurement_action_version', ['status'], unique=False)
    op.create_index('idx_procurement_tracker_agreement_id_status', 'procurement_tracker', ['agreement_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_agreement_id'), 'procurement_tracker', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_status'), 'procurement_tracker', ['status'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_agreement_id'), 'procurement_tracker_version', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_procurement_tracker_version_status'), 'procurement_tracker_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_tracker_version_status'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_version_agreement_id'), table_name='procurement_tracker_version')
    op.drop_index(op.f('ix_procurement_tracker_status'), table_name='procurement_tracker')
    op.drop_index(op.f('ix_procurement_tracker_agreement_id'), table_name='procurement_tracker')
    op.drop_index('idx_procurement_tracker_agreement_id_status', table_name='procurement_tracker')
    op.drop_index(op.f('ix_procurement_action_version_status'), table_name='procurement_action_version')
    op.drop_index(op.f('ix_procurement_action_version_award_type'), table_name='procurement_action_version')
    op.drop_index(op.f('ix_procurement_action_version_agreement_id'), table_name='procurement_action_version')
    op.drop_index(op.f('ix_procurement_action_status'), table_name='procurement_action')
    op.drop_index(op.f('ix_procurement_action_award_type'), table_name='procurement_action')
    op.drop_index('ix_procurement_action_agreement_id_award_type_status', table_name='procurement_action')
    op.drop_index(op.f('ix_procurement_action_agreement_id'), table_name='procurement_action')
    # ### end Alembic commands ###
