INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (1, 'Child Care', 'CC', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (2, 'Division of Economic Independence', 'DEI', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (3, 'Office of the Director', 'OD', null, current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (4, 'Division of Child and Family Development', 'DFCD', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (5, 'Division of Family Strengthening', 'DFS', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (6, 'Division of Data and Improvement', 'DDI', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (7, 'Non-OPRE Division', 'OTHER', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (8, 'Division of Data Privacy', 'DDP', current_timestamp, current_timestamp, 1, null, 0);
INSERT INTO ops.division_version (id, name, abbreviation, created_on, updated_on, transaction_id, end_transaction_id, operation_type) VALUES (9, 'Division of Data Governance', 'DDG', current_timestamp, current_timestamp, 1, null, 0);
