INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (1, 'Child Welfare Research', 'CWR', 'IN_PROCESS', 4, e'             The promotion of children’s safety, permanence, and well-being are the principles that guide child             welfare practice and policy. ACF seeks to improve the safety, permanency, and well-being of children through             leadership, support for necessary services, and productive partnerships with states, tribes, and              communities. ACF’s Children’s Bureau has the primary responsibility for administering federal programs             that support state child welfare services. ACF provides matching federal funds to states, tribes, and             communities to help them operate every aspect of their child welfare systems. This includes the             prevention of child abuse and neglect, the support of permanent placements through adoption and             subsidized guardianship, and the creation and maintenance of information systems necessary to support             these programs. ACF supports a number of research and evaluation activities as well as learning from a             broad array of other activities relevant to child welfare such as performance management, technical             assistance, stakeholder engagement, site monitoring, developing systems to oversee and use data, and             continuous quality improvement. ACF also analyzes and reports information on administrative data             such as the National Child Abuse and Neglect Data System (NCANDS), Adoption and Foster Care             Analysis and Reporting System (AFCARS), and National Youth in Transition Database (NYTD)

Over the past several decades, research and evaluation activities in child welfare have increased             significantly. This body of knowledge has shown that child maltreatment is a complex problem associated             with multiple, interrelated risk and protective factors at individual, family, community, and contextual             levels.  This research has demonstrated that child abuse and neglect may have long-lasting and cumulative             effects on the well-being of children into adulthood. There is burgeoning research examining the             potential effectiveness of preventative and intervention treatments to improve the safety, stability,             and well-being of children and their families.

OPRE’s child welfare research portfolio includes research on children who are maltreated or who are at             risk for child maltreatment; children and families who come to the attention of child protective services;             and children and families who are receiving child welfare services either in their families of origin or             in substitute care settings. OPRE also partners with the Children’s Bureau to conduct research covering a             broad array of topics, including identification of antecedents and consequences of child maltreatment,             strategies for prevention of maltreatment, and service needs and service outcomes for children who come             to the attention of child welfare.        ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (2, 'Head Start', 'HS', 'IN_PROCESS', 4, e'            Established in 1965, Head Start was designed to promote the school readiness of children, ages three to            five, from families with low income, by supporting the development of the whole child through high-quality,            comprehensive services. In 1994, the Early Head Start program was established to provide the same            comprehensive services to families with low income who have infants and toddlers, as well as pregnant            women. Today, ACF’s Office of Head Start oversees approximately 1,600 Head Start and Early Head Start            grant recipients that serve nearly one million children, birth to age five, and their families.

For over 50 years, Head Start research has examined the impact of its programs as a whole, how those            impacts vary for different populations, communities, or program characteristics, how programs deliver            services, the quality of services, the qualifications of staff, and the characteristics and needs of            children and families. In doing so, Head Start research targets strategies for improving program quality            and child and family outcomes. Through partnerships between researchers and local programs, Head Start            develops and evaluates innovations in Head Start practice related to infant mental health, parenting,            dual language learning, curricular enhancements, caregiver-child interactions, dual-generation approaches,            and other topics. This growing research base provides valuable information not only for guiding program            improvements in Head Start itself, but also for the larger field of early care and education.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (3, 'Child Care', 'CC', 'IN_PROCESS', 4, e'            Quality child care and early education programs are a critical resource for families, support young            children’s development in a variety of domains, and assist parents in accessing comprehensive services            for their families.

ACF supports working families with low incomes by providing funding and implementing policies intended            to increase access to affordable, quality child care and early education programs serving children from            birth through age 13. ACF’s Office of Child Care administers the Child Care and Development Fund (CCDF),            which is a block grant authorized under the Child Care and Development Block Grant (CCDBG). In 2021,            CCDF made $9.5 billion available to state, territory, and tribal governments to support children and            their families by paying for child care that meets families’ needs and supports children’s development            and well-being. CCDF also provides funding to improve the quality of care by supporting efforts such as            child care licensing, quality improvement systems, and training and education for child care workers.

OPRE’s child care research portfolio aims to increase knowledge about the efficacy of child care            subsidy policies and programs in enhancing employment and economic self-sufficiency of low-income            families, and in improving quality in child care and early education settings to support learning and            development of children from birth through age 13. Research demonstrating the link between subsidies,            quality child care and early education, and positive child and family outcomes has encouraged efforts to            enhance early care and education programs through investments of CCDF quality set-aside funds.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (4, 'Welfare Research', 'WR', 'IN_PROCESS', 2, e'        The Personal Responsibility and Work Opportunity Reconciliation Act (PRWORA) of 1996 established the        Temporary Assistance for Needy Families (TANF) program to help children and families with low incomes        achieve economic security and stability. Under TANF, states, eligible territories, and tribes receive block        grant funds to provide cash assistance to eligible families and a range of other services to accomplish        one of the program’s four broad purposes. While TANF jurisdictions must meet certain work        participation and cost sharing requirements, they have considerable flexibility to design and implement        programs that best serve their distinct communities.

PRWORA also authorized funding for welfare research, evaluation, and technical assistance activities.        The Consolidated Appropriations Act of 2017 significantly increased the amount of this funding by        establishing a set-aside of 0.33% of the TANF block grant to support these activities. The legislation        directs ACF to use these funds for TANF-related research and evaluation; the development of a “what        works clearinghouse” of effective approaches for moving welfare recipients into work; technical        assistance to support TANF programs and services; and federal administration of these activities. The        set-aside and the research, evaluation, and technical assistance it funds is referred to as the ‘Welfare        Research’ portfolio.

OPRE’s Division of Economic Independence partners with the Office of Family Assistance (OFA) to carry        out the Welfare Research portfolio. OFA administers the TANF program; collects and analyzes program        data on caseloads, expenditures, and work participation; and provides programmatic technical        assistance to TANF jurisdictions. OPRE conducts rigorous research and evaluation to better understand        how TANF and other human services programs can best support the self-sufficiency and economic well-        being of children and families with low incomes. These studies address a range of topics including TANF        program administration; employment, training, and occupational skill-building programs; coordination        across social services delivery systems; and the role of broader social context and environmental factors.        Within these and related topics, OPRE funds experimental impact evaluations, implementation        evaluations, and descriptive research projects aimed at informing the design and implementation of        TANF programs and services. OPRE also supports activities to build the research and evaluation capacity        of TANF and other human services programs, and to communicate findings from the Welfare Research        portfolio to the broader field.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (5, 'Adolescent Development Research', 'ADR', 'IN_PROCESS', 5, e'          Despite recent declines in teen childbirth rates, adolescent pregnancy rates in the United States are much          higher than in other western industrialized nations. More research and programming innovations are needed to          identify effective ways to decrease rates of adolescent sexual risk behavior and associated negative          outcomes. Since 2009, ACF has supported research and evaluation efforts in adolescent pregnancy prevention          and, more recently, sexual risk avoidance. ACF supports a number of research and evaluation activities as          well as learning from a broad array of other activities such as performance management, technical          assistance, stakeholder engagement, site monitoring, and program improvement.

To help reduce non-marital sexual activity, adolescent pregnancies, sexually transmitted infections,          and other risk behaviors, ACF’s Family and Youth Services Bureau oversees two funding streams within the          Adolescent Pregnancy Prevention (APP) program: the Personal Responsibility Education Program (PREP) and the          Sexual Risk Avoidance Education (SRAE) Program. PREP programs educate adolescents on both abstinence and          contraception for the prevention of pregnancy and sexually transmitted infections. The SRAE Program funds          projects that exclusively implement sexual risk avoidance education that teaches youth how to voluntarily          refrain from non-marital sexual activity, empower youth to make healthy decisions, and provide tools and          resources to prevent youth engagement in other risky behaviors.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (6, 'Healthy Marriage & Responsible Fatherhood', 'HMRF', 'IN_PROCESS', 5, e'            The Healthy Marriage and Responsible Fatherhood (HMRF) program is part of ACF’s strategy to improve the            long-term well-being of children and families. HMRF is a $150 million discretionary grant program            originally authorized under the Deficit Reduction Act of 2005 and reauthorized under the Claims Resolution            Act of 2010. ACF supports a number of research and evaluation activities as well as learning from a broad            array of other activities such as performance management, technical assistance, stakeholder engagement,            site monitoring, and continuous quality improvement.

A large body of research has shown that, on average, children raised in stable families with involved            parents and caregivers have better outcomes on a range of measures, even into adulthood. Research has also            identified dimensions of couples’ relationship functioning (e.g., positive communication, effective            conflict management, problem solving, etc.) that could be modified or enhanced through relationship-focused            educational programming. Some evaluations have found that such programming can produce improvement in            multiple dimensions of relationship quality and stability. In recent decades, efforts to support and            promote supportive fathering have been spurred by research that shows a link between supportive fathering            and positive child outcomes. Thus, fatherhood programs aim to provide resources and supports to fathers            around healthy marriage and relationships, parenting, and economic stability.

OPRE’s strengthening families, healthy relationships and marriages, and fatherhood portfolio includes            research and evaluation on topics such as family formation and stability, co-parenting, marriage,            fatherhood, and violence in relationships. This research helps us develop more accurate knowledge of the            unique experiences of populations served by HMRF programs through a better understanding their strengths.            Studies include a focus on the implications of programs and policies (including welfare policies) for            child, adult, and family well-being.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (7, 'Home Visiting', 'HV', 'IN_PROCESS', 5, e'            Home visiting is a service delivery strategy that aims to support the healthy development and well-being            of children and families. While each home visiting model has its unique aspects, in general, home visiting            involves three main intervention activities conducted through one-on-one interactions between home            visitors and families: assessing family needs, educating and supporting parents, and referring families to            needed services in the community. Early childhood home visiting programs aim to improve a wide range of            outcomes including maternal health, child health and development, child maltreatment prevention, and family            economic self-sufficiency.

Federal investment in home visiting — and related research and evaluation — has greatly expanded            through the Maternal, Infant, and Early Childhood Home Visiting (MIECHV) Program, which was established in            2010. The MIECHV Program supports home visiting for expectant and new parents with children up to            kindergarten entry age who live in communities that are at-risk for poor maternal and child health            outcomes. Families choose to participate in home visiting programs, and partner with health, social            service, and child development professionals to set and achieve goals that improve their health and            well-being. MIECHV is administered by the Health Resources and Services Administration (HRSA) in            collaboration with ACF. HRSA oversees the state and territory MIECHV Program, which provides grants to            states, territories, and eligible non-profit organizations to develop and implement statewide home visiting            programs. ACF oversees the Tribal MIECHV program, which provides grants to tribes, tribal organizations,            and Urban Indian Organizations to develop, implement, and evaluate home visiting programs in American            Indian and Alaska Native communities.

In collaboration with HRSA and with ACF’s Tribal MIECHV program, ACF’s Office of Planning, Research,            and Evaluation manages and partners on research, evaluation, and technical assistance activities related            to MIECHV and home visiting.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (8, 'Data Governance', 'DG', 'IN_PROCESS', 6, e'            Data governance is the mechanism (i.e., structures, processes, and policies) for organizational staff and            leadership to manage data throughout the data lifecycle, while ensuring its security, exploring            opportunities to share data for evidence-building activities, and using data for programmatic, evaluation            and research purposes. ACF’s goals related to data governance are to make data more usable, accessible,            and protected to meet the operational and evidence-building data governance needs of ACF; meet the            operational and evidence-building data governance needs of ACF offices;  and promote the reuse of ACF            data for evidence-building purposes at the state, local, tribal, territory, and grant recipient levels.

The Data Governance Team within DDI has primary responsibility for coordinating ACF\'s data governance            activities. For the purpose of OPS, this portfolio covers projects that advance ACF’s progress in meeting            its data governance goals. This portfolio is led by the OPRE Division of Data and Improvement.      ', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (9, 'Office Of The Director', 'OD', 'IN_PROCESS', 3, '', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (10, 'Privacy & Security', 'PS', 'IN_PROCESS', 8, '', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (11, 'Data Governance', 'DG', 'IN_PROCESS', 9, '', current_timestamp, current_timestamp);
INSERT INTO ops.portfolio (id, name, abbreviation, status, division_id, description, created_on, updated_on) VALUES (12, 'Not A Specific Portfolio', 'NON-OPRE', 'IN_PROCESS', 3, '', current_timestamp, current_timestamp);
