# Generated by Django 4.1.1 on 2022-09-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ops_site", "0004_alter_commonaccountingnumber_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                ("purpose", models.TextField(blank=True, default="")),
                ("nickname", models.CharField(max_length=30)),
                (
                    "arrangement_type",
                    models.CharField(
                        choices=[
                            ("OPRE Appropriation", "Opre Appropriation"),
                            ("Cost Share", "Cost Share"),
                            ("IAA", "Iaa"),
                            ("IDDA", "Idda"),
                            ("MOU", "Mou"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "authorizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorizers",
                        to="ops_site.fundingpartner",
                    ),
                ),
                ("funding_source", models.ManyToManyField(to="ops_site.fundingsource")),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cans",
                        to="ops_site.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CANs",
            },
        ),
        migrations.AlterField(
            model_name="canfiscalyear",
            name="can",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ops_site.can"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="cans",
            field=models.ManyToManyField(related_name="contracts", to="ops_site.can"),
        ),
        migrations.AlterField(
            model_name="contractlineitemfiscalyearpercan",
            name="can",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items_fy",
                to="ops_site.can",
            ),
        ),
        migrations.DeleteModel(
            name="CommonAccountingNumber",
        ),
    ]
