import ReactMarkdown from "react-markdown";

const TableOfContents = ({ data }) => {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ%".split("");
    const existingLetters = new Set(data.map((item) => item.heading[0].toUpperCase()));

    return (
        <div className="display-flex flex-wrap margin-bottom-4 flex-justify-center">
            {alphabet.map((letter) => (
                <div
                    key={letter}
                    className="margin-right-3 margin-bottom-1"
                >
                    {existingLetters.has(letter) ? (
                        <a
                            href={`#section-${letter}`}
                            className="text-primary"
                        >
                            {letter}
                        </a>
                    ) : (
                        <span className="text-gray-30">{letter}</span>
                    )}
                </div>
            ))}
        </div>
    );
};

const Glossary = () => {
    // Sort data alphabetically, but put items starting with % at the end
    const sortedData = [...data].sort((a, b) => {
        const aStartsWithPercent = a.heading.startsWith("%");
        const bStartsWithPercent = b.heading.startsWith("%");

        if (aStartsWithPercent && !bStartsWithPercent) return 1;
        if (!aStartsWithPercent && bStartsWithPercent) return -1;
        return a.heading.localeCompare(b.heading);
    });

    let currentLetter = "";

    return (
        <>
            <h2 className="margin-bottom-4">Glossary</h2>
            <TableOfContents data={sortedData} />
            <section className="usa-prose">
                {sortedData.map((item) => {
                    const firstLetter = item.heading[0].toUpperCase();
                    let letterHeader = null;
                    if (firstLetter !== currentLetter) {
                        currentLetter = firstLetter;
                        letterHeader = (
                            <h3
                                id={`section-${firstLetter}`}
                                className="margin-top-4 margin-bottom-2"
                            >
                                {firstLetter}
                            </h3>
                        );
                    }

                    return (
                        <section key={item.heading}>
                            {letterHeader}
                            <dl>
                                <dt className="text-primary text-bold">{item.heading}</dt>
                                <dd className="margin-left-0 line-height-body-3 margin-top-05 margin-bottom-3">
                                    <ReactMarkdown>{item.content}</ReactMarkdown>
                                </dd>
                            </dl>
                        </section>
                    );
                })}
            </section>
        </>
    );
};

// Markdown Guide https://www.markdownguide.org/basic-syntax/
const data = [
    {
        heading: "Agreement",
        content: `
An agreement is a defined piece of internal or external work, often between OPRE and other contractors. Agreements can be grouped together as part of a broader project, but they can also exist as standalone agreements not associated with any specific project. Agreements are linked to Divisions and Portfolios through CANs used within each budget line. There are three main types of agreements: Contracts, Grants, and IAAs.
        `
    },
    {
        heading: "Appropriation",
        content: ` The date in which money was appropriated to OPRE from Congress`
    },
    {
        heading: "BL",
        content: `Budget Line`
    },
    {
        heading: "BL ID #",
        content: ` Budget Line ID # - a reference number auto-generated by OPS when a new budget line is added to an agreement`
    },
    {
        heading: "Budget Line Status",
        content: `
The status of a budget line. These are the current statuses in OPS:

- Draft - BL is just a placeholder or idea, not subtracted from the budget, can be edited freely without approval
- Planned - BL is subtracted from the budget, planned to move forward but still can change, edits require a Division Director approval
- Executing - BL is in the procurement process, in progress to be formally committed
- Obligated - BL is committed in the signed award and can be invoiced against
- In Review - BL has pending edits or a pending status change request
        `
    },
    { heading: "CAN", content: `Common Accounting Number` },
    {
        heading: "CLIN",
        content: `Contract Line Item Number which aligns Budget Lines to line items in an awarded contract. They are used as a reference point between the Procurement Shop and OPRE.`
    },
    { heading: "First Award", content: `The date of the first contract awarded within a project` },
    {
        heading: "Funding ID",
        content: `A reference number auto-generated by OPS when funding received (to OPRE) is entered towards a CANs FY Budget `
    },
    { heading: "FY", content: `Fiscal Year` },
    {
        heading: "My Budget Lines",
        content: `
A list of budget lines specific to each user:

- For CORs and other team members it displays any budget lines from agreements they are listed as a Team Member on
- For Team Leaders it displays any budget lines managed by their Portfolio
- For DDs it displays any budget lines managed by Portfolios within their Division
        `
    },
    {
        heading: "My CANs",
        content: `
A list of CANs specific to each user:

- For CORs and other team members it displays any CANs from agreements they are listed as a Team Member on
- For Team Leaders it displays any CANs managed by their Portfolio
- For DDs it displays any CANs managed by Portfolios within their Division
        `
    },
    { heading: "Next Budget Line", content: `Budget line with the next upcoming obligate by date` },
    { heading: "Next Obligate By", content: `The next upcoming need by date for a budget line using a specific CAN` },
    {
        heading: "New Funding",
        content: `New money that is appropriated into a 1 year CAN (not left over from another FY)`
    },
    {
        heading: "Obligate By Date",
        content: `Formerly known as Need By Date - the date the budget line needs to be obligated before`
    },
    {
        heading: "Optional Services Component (OSC)",
        content: `A service component that is optional or might change based on the outcomes of the work in previous services components / the first services component can never be optional`
    },
    { heading: "Period of Performance-Start", content: `The first day that work for this service component begins` },
    { heading: "Period of Performance-End", content: `The last day of work for this service component` },
    {
        heading: "Portfolio",
        content: `A Research Portfolio at OPRE, typically grouped by research area and/or funding stream.  These are the current portfolios in OPS:
- Portfolios within the Division of Child & Family Development (DCFD)
  - Child Welfare Research
  - Head Start Research
  - Child Care Research
- Portfolios within the Division of Economic Independence (DEI)
  - Welfare Research
- Portfolios within the Division of Family Strengthening (DFS)
  - Adolescent Development Research
  - Healthy Marriage and Responsible Fatherhood Research
  - Home Visiting Research
- Portfolios within the Division of Data and Improvement (DDI)
  - Program Support
  - Data Governance
        `
    },
    {
        heading: "Project",
        content: `
 A project is a body of work composed of agreements that share a common topic or theme. Types of projects in OPS include:

-  Research Projects- projects that support an OPRE research goal
- Admin/Support Projects - projects that account for internal costs like rent or website development
 `
    },
    { heading: "Project Total", content: `The total of all agreements within a project` },
    { heading: "Previous FYs Carry-Forward", content: `Left-over or carry-forward money from a multi-year CAN` },
    {
        heading: "SC",
        content: `Services Components - Describe detailed work outlined in an agreement. All Services Components have a Period of Performance (start and end date) that describes when the work will be completed. There are two types of SC formats: Non-Severable and Severable.`
    },
    { heading: "Spending ", content: `The sum of Budget Lines in Planned, Executing and Obligated Status` },
    {
        heading: "% of Budget",
        content: `The percent of a portfolio’s fiscal year budget that the budget line is spending`
    },
    {
        heading: "Bravo",
        content: `whatever this is`
    }
];

export default Glossary;
