import ReactMarkdown from "react-markdown";

const TableOfContents = ({ data }) => {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ%".split("");
    const existingLetters = new Set(data.map((item) => item.heading[0].toUpperCase()));

    return (
        <div className="display-flex flex-wrap margin-bottom-4 flex-justify-center">
            {alphabet.map((letter) => (
                <div
                    key={letter}
                    className="margin-right-3 margin-bottom-1"
                >
                    {existingLetters.has(letter) ? (
                        <a
                            href={`#section-${letter}`}
                            className="text-primary"
                        >
                            {letter}
                        </a>
                    ) : (
                        <span className="text-gray-30">{letter}</span>
                    )}
                </div>
            ))}
        </div>
    );
};

const Glossary = () => {
    // Sort data alphabetically, but put items starting with % at the end
    const sortedData = [...data].sort((a, b) => {
        const aStartsWithPercent = a.heading.startsWith("%");
        const bStartsWithPercent = b.heading.startsWith("%");

        if (aStartsWithPercent && !bStartsWithPercent) return 1;
        if (!aStartsWithPercent && bStartsWithPercent) return -1;
        return a.heading.localeCompare(b.heading);
    });

    let currentLetter = "";

    return (
        <>
            <h2 className="margin-bottom-4">Glossary</h2>
            <TableOfContents data={sortedData} />
            <section className="usa-prose">
                {sortedData.map((item) => {
                    const firstLetter = item.heading[0].toUpperCase();
                    let letterHeader = null;
                    if (firstLetter !== currentLetter) {
                        currentLetter = firstLetter;
                        letterHeader = (
                            <h3
                                id={`section-${firstLetter}`}
                                className="margin-top-4 margin-bottom-2"
                            >
                                {firstLetter}
                            </h3>
                        );
                    }

                    return (
                        <section key={item.heading}>
                            {letterHeader}
                            <dl>
                                <dt className="text-primary text-bold">{item.heading}</dt>
                                <dd className="margin-left-0 line-height-body-3 margin-top-05 margin-bottom-3">
                                    <ReactMarkdown>{item.content}</ReactMarkdown>
                                </dd>
                            </dl>
                        </section>
                    );
                })}
            </section>
        </>
    );
};

// Markdown Guide https://www.markdownguide.org/basic-syntax/
const data = [
    {
        heading: "Agreement",
        content: `
An agreement is a defined piece of internal or external work, often between OPRE and other contractors. Agreements can be grouped together as part of a broader project, but they can also exist as standalone agreements not associated with any specific project. Agreements are linked to Divisions and Portfolios through CANs used within each budget line. There are three main types of agreements: Contracts, Grants, and IAAs.
        `
    },
    {
        heading: "Appropriation",
        content: ` The date in which money was appropriated to OPRE from Congress`
    },
    {
        heading: "BL",
        content: `Budget Line`
    },
    {
        heading: "BL ID #",
        content: ` Budget Line ID # - a reference number auto-generated by OPS when a new budget line is added to an agreement`
    },
    {
        heading: "Budget Line Status",
        content: `
The status of a budget line. These are the current statuses in OPS:

- Draft - BL is just a placeholder or idea, not subtracted from the budget, can be edited freely without approval
- Planned - BL is subtracted from the budget, planned to move forward but still can change, edits require a Division Director approval
- Executing - BL is in the procurement process, in progress to be formally committed
- Obligated - BL is committed in the signed award and can be invoiced against
- In Review - BL has pending edits or a pending status change request
- Planned MOD - BL is accounted for in the award, but will require a modification in order to be executed when the FY it is planned for approaches
        `
    },
    { heading: "CAN", content: `Common Accounting Number` },
    {
        heading: "CLIN",
        content: `Contract Line Item Number which aligns Budget Lines to line items in an awarded contract. They are used as a reference point between the Procurement Shop and OPRE.`
    },
    { heading: "First Award", content: `The date of the first contract awarded within a project` },
    {
        heading: "Funding ID",
        content: `A reference number auto-generated by OPS when funding received (to OPRE) is entered towards a CANs FY Budget `
    },
    { heading: "FY", content: `Fiscal Year` },
    {
        heading: "My Budget Lines",
        content: `
A list of budget lines specific to each user:

- For CORs and other team members it displays any budget lines from agreements they are listed as a Team Member on
- For Team Leaders it displays any budget lines managed by their Portfolio
- For DDs it displays any budget lines managed by Portfolios within their Division
        `
    },
    {
        heading: "My CANs",
        content: `
A list of CANs specific to each user:

- For CORs and other team members it displays any CANs from agreements they are listed as a Team Member on
- For Team Leaders it displays any CANs managed by their Portfolio
- For DDs it displays any CANs managed by Portfolios within their Division
        `
    },
    { heading: "Next Budget Line", content: `Budget line with the next upcoming obligate by date` },
    { heading: "Next Obligate By", content: `The next upcoming need by date for a budget line using a specific CAN` },
    {
        heading: "New Funding",
        content: `New money that is appropriated into a 1 year CAN (not left over from another FY)`
    },
    {
        heading: "Obligate By Date",
        content: `Formerly known as Need By Date - the date the budget line needs to be obligated before`
    },
    {
        heading: "Optional Services Component (OSC)",
        content: `A service component that is optional or might change based on the outcomes of the work in previous services components / the first services component can never be optional`
    },
    { heading: "Period of Performance-Start", content: `The first day that work for this service component begins` },
    { heading: "Period of Performance-End", content: `The last day of work for this service component` },
    {
        heading: "Portfolio",
        content: `A Research Portfolio at OPRE, typically grouped by research area and/or funding stream.  These are the current portfolios in OPS:
- Portfolios within the Division of Child & Family Development (DCFD)
  - Child Welfare Research
  - Head Start Research
  - Child Care Research
- Portfolios within the Division of Economic Independence (DEI)
  - Welfare Research
- Portfolios within the Division of Family Strengthening (DFS)
  - Adolescent Development Research
  - Healthy Marriage and Responsible Fatherhood Research
  - Home Visiting Research
- Portfolios within the Division of Data and Improvement (DDI)
  - Program Support
  - Data Governance
        `
    },
    {
        heading: "Project",
        content: `
 A project is a body of work composed of agreements that share a common topic or theme. Types of projects in OPS include:

- Research Projects- projects that support an OPRE research goal
- Admin/Support Projects - projects that account for internal costs like rent or website development`
    },
    { heading: "Project Total", content: `The total of all agreements within a project` },
    { heading: "Previous FYs Carry-Forward", content: `Left-over or carry-forward money from a multi-year CAN` },
    {
        heading: "SC",
        content: `Services Components - Describe detailed work outlined in an agreement. All Services Components have a Period of Performance (start and end date) that describes when the work will be completed. There are two types of SC formats: Non-Severable and Severable.`
    },
    { heading: "Spending ", content: `The sum of Budget Lines in Planned, Executing and Obligated Status` },
    {
        heading: "% of Budget",
        content: `The percent of a portfolio’s fiscal year budget that the budget line is spending`
    },
    {
        heading: "Contract Type",
        content: `The method the government will use to pay the vendor for their services. Contract types may vary according to the degree and timing of the responsibility assumed by the contractor for the costs of performance; and the amount and nature of the profit incentive offered to the contractor for achieving or exceeding specified standards or goals. Source: [FAR]`
    },
    {
        heading: "Firm Fixed Price (FFP)",
        content: `A contract type utilized when you can clearly outline the level of effort needed to complete the contract at the time of award. FFP is the preferred methodology by the government because maximum risk and full responsibility for all costs and resulting profit or loss falls on the contractor as opposed to the government.`
    },
    {
        heading: "Time & Materials (T&M)",
        content: `A contract type utilized when you have a cost-reimbursement type contract where you pay the vendor for all of their time and materials, every single labor hour expanded, every single material utilized. This is one of the least preferred government contract types because there is more risk to the government through undefined cost incurred to the government, which contract ceilings help to alleviate - only used for commercial contracts without auditing`
    },
    {
        heading: "Cost Plus Fixed Fee (CPFF)",
        content: `A contract type utilized in a cost-reimbursement type environment where the fee negotiated is at time of award for certain services to be completed successfully. This is utilized when we are unable to estimate the level of effort at time of award.`
    },
     {
        heading: "Cost Plus Award Fee (CPAW)",
        content: `A contract type utilized in a cost-reimbursement type environment where the fee negotiated is at time of award for certain services to be completed successfully in a performance based environment.`
    },
     {
        heading: "Service Requirement Type",
        content: `The format for services components on an agreement such as Severable or Non-Severable which determine how the contract will be completed`
    },
    {
        heading: "Severable",
        content: `A service requirement type where the contract can be cut-off or severed and value is still provided. In OPS, the services component format for this type is base period 1, option period 2, etc.`
    },
    {
        heading: "Non-Severable",
        content: `A service requirement type where there is no value if the contract gets severed so it must be completed in its entirety. The entire contract must be completed in order for value to be provided. In OPS, the services component format for this type is SC1, SC2, OSC3, etc.`
    },
    {
        heading: "Product Service Code",
        content: `A code used to describe products, services, and research and development (R&D) purchased by the federal government. These codes indicate “what” was bought for each contract action reported in the Federal Procurement Data System (FPDS)`
    },
    {
        heading: "Other Scientific and Technical Consulting Services",
        content: `A product service code used for research contracts`
    },
    {
        heading: "Convention and Trade Shows",
        content: `A product service code used for conferences, trade shows and meetings`
    },
    {
        heading: "NAICS Code",
        content: `A classification of services or supplies being bought. For example, some classifications have designations for small business criteria. NAICS stands for North American Industry Classification System.`
    },
    {
        heading: "Program Support Code",
        content: `A classification of services that will pre-populate the NAICS code in OPS`
    },
    {
        heading: "Procurement Shop",
        content: `A department or team within the government responsible for acquiring goods and services. In OPS, the Procurement Shops used by OPRE are:
        - Office of Acquisition Management Services (OAMS) formerly known as Program Support Center (PSC) 
        - Government Contracting Services (GCS)
        - National Institute of Health (NIH)
        - Interior Business Center (IBC) 
        `
    },
    {
        heading: "Program Support Center (PSC)",
        content: `A procurement shop currently known as Office of Acquisition Management Services (OAMS) which is used for legacy OPRE procurements. Only modifications of legacy PSC contracts should be done at this shop.`
    },
     {
        heading: "Office of Acquisition Management Services (OAMS)",
        content: `A procurement shop formerly known as Program Support Center (PSC). Only modifications of legacy PSC contracts should be done at this shop.`
    },
     {
        heading: "Government Contracting Services (GCS)",
        content: `A procurement office that resides in ACF and is the main contracting office supporting OPRE. All new actions should utilize this shop unless told otherwise.`
    },
     {
        heading: "National Institute of Health (NIH)",
        content: `A procurement shop used for medical research`
    },
     {
        heading: "Interior Business Center (IBC)",
        content: `A procurement shop used for federal shared services that operates under a fee-for-service, full cost recovery business model, offering Acquisition, Financial Management and Human Resources systems and services to federal organizations.`
    },
    {
        heading: "Reason for Agreement",
        content: `The reason a new agreement is created. The options for Reason for Agreement in OPS include:
        - New Requirement
        - Recompete
        - Logical Follow On
        `
    },
     {
        heading: "New Requirement",
        content: `A reason for agreement used when there is not an already established project and a new award is the desired outcome of the project. This is used when a project has never been done before.`
    },
    {
        heading: "Recompete",
        content: `A reason for agreement used when a project’s period of performance is ending but the services are still needed. The Government would award the work for continued sources in a competitive environment.`
    },
     {
        heading: "Logical Follow On",
        content: `A reason for agreement used when a project’s period of performance is ending but the services are still needed. The Government would award the work for continued sources in a non-competitive environment to the incumbent vendor.`
    },
    {
        heading: "Fee Rate",
        content: `The fee rate applied to budget lines depending on which Procurement Shop the agreement is using.`
    },
    {
        heading: "Appropriation FY",
        content: `The fiscal year a CAN’s funding was appropriated from congress.`
    },
    {
        heading: "Active Period",
        content: `The amount of time a CAN is active and its funding can be obligated. For example, the funding in a 1 year CAN can be obligated for 1 FY and then it expires. Funding in a 5 Year CAN can be obligated for 5 FYs, and then it expires.`
    },
    {
        heading: "Funding Method",
        content: `The way a CAN is funded, direct or reimbursable`
    },
    {
        heading: "Funding Type",
        content: `Whether a CAN’s funding has been required by law (mandatory) or voted on (discretionary)`
    },
    {
        heading: "Fund Code",
        content: `A 14 digit code which is comprised of multiple codes that provide details for a CAN including funding and duration information.`
    },
    {
        heading: "Allowance",
        content: `A special functional classification designed to include an amount to cover possible requirements which remains undistributed until the contingency on which it is based occurs.`
    },
    {
        heading: "Allotment",
        content: `A unique code used to identify a specific allocation of funds within a budget, essentially signifying a designated portion of money earmarked for a particular program or project within the agency.`
    },
    {
        heading: "Funding Source",
        content: `Determines how a CAN is funded from congress:
        - Direct = Congress direct to OPRE
        - ACF = Congress to another office in ACF
        - ACF MOU = ​​Congress to another office in ACF with specific requirements on who the money has to go to/towards
        - HHS = Congress to another agency internal to HHS
        - Other = Congress to another agency external to HSS
        `
    },
    {
        heading: "Partner",
        content: `Who OPRE is partnering with to utilize the funding in a CAN.`
    },
    {
        heading: "Method of Transfer",
        content: `How funding for a CAN is received, options in OPS include:
        - Directly appropriated (Direct)
        - Cost Sharing (from another office within ACF)
        - Inter-Agency-Agreement (IAA) (from another agency in relation to contracts)
        - Inter-Departmental-Delegation of Authority (IDDA) (from another agency in relation to grants)
        - Other
        `
    },
    {
        heading: "Funding Received YTD",
        content: `Funding that has been received by OPRE towards a CANs FY Budget. This means the money is in OPRE’s bank account, and checks can be written against the available funds.`
    },
    {
        heading: "Research Project",
        content: `A project at OPRE that is research-focused such as an explorative study or research report.`
    },
    {
        heading: "Admin & Support Project",
        content: `A project at OPRE that is administrative related such as rent or website development. These projects are typically shared costs across portfolios.`
    }
];

export default Glossary;
