name: Set up Python
description: Installs Python3 and dependencies defined in the Pipfile
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@03bb6152f4f691b9d64579a1bd791904a083c452 # tag: v4.3.0
      with:
        python-version: '3.13'
        cache: pipenv
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Install Pipenv dependencies
      shell: bash
      working-directory: ./backend/ops_api
      run: pipenv install --dev
