# Generated by Django 4.0.4 on 2022-06-03 17:54
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CANAmount",
            new_name="CANFiscalYear",
        ),
        migrations.RenameModel(
            old_name="CANInfo",
            new_name="CommonAccountingNumber",
        ),
        migrations.AlterModelOptions(
            name="canfiscalyear",
            options={"verbose_name_plural": "CANs (fiscal year)"},
        ),
        migrations.AlterModelOptions(
            name="commonaccountingnumber",
            options={"verbose_name_plural": "CANs"},
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "cans",
                    models.ManyToManyField(
                        related_name="contracts", to="ops.commonaccountingnumber"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="ops.contract",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractLineItemFiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField()),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_years",
                        to="ops.contractlineitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractLineItemFiscalYearPerCAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funding", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "can",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items_fy",
                        to="ops.commonaccountingnumber",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cans",
                        to="ops.contractlineitemfiscalyear",
                    ),
                ),
            ],
        ),
    ]
