# Generated by Django 4.1.1 on 2022-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(null=True),
        ),
    ]
