# Generated by Django 4.1 on 2022-08-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0003_portfolio_commonaccountingnumber_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonaccountingnumber",
            name="portfolio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cans",
                to="ops.portfolio",
            ),
        ),
    ]
