# Generated by Django 4.1 on 2022-08-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ops_site", "0002_significant_model_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In-Process", "In-Process"),
                            ("Not-Started", "Not-Started"),
                            ("Sandbox", "Sandbox"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "current_fiscal_year_funding",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commonaccountingnumber",
            name="portfolio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolio",
                to="ops_site.portfolio",
            ),
        ),
    ]
