# Generated by Django 4.1 on 2022-08-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops_site", "0003_portfolio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={},
        ),
    ]
