# Generated by Django 3.2.6 on 2021-09-01 23:27

import os

from django.db import migrations
from csv import DictReader
from ops_site.models import Agency


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0001_initial'),
    ]

    operations = []
