# Generated by Django 4.0.4 on 2022-06-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops_site", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CANAmount",
            new_name="CANFiscalYear",
        ),
        migrations.RenameModel(
            old_name="CANInfo",
            new_name="CommonAccountingNumber",
        ),
    ]
