# Generated by Django 3.2.6 on 2021-09-01 23:27

import os

from opre_ops.settings.local import BASE_DIR
from django.db import migrations
from csv import DictReader
from ops_site.models import Agency
from pathlib import Path

def seed_agencies(apps, schema_editor):
    filename = os.path.join('ops_site', 'migrations', 'seed_data', 'agencies.csv')
    with open(filename, encoding="utf-8-sig") as read_obj:
        csv_dict_reader = DictReader(read_obj)
        for row in csv_dict_reader:
            agency = Agency(name=row.get("Name"), nickname=row.get("Nickname"))
            agency.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_agencies)
    ]
