# Generated by Django 3.2.6 on 2021-09-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0002_auto_20210901_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'agencies'},
        ),
    ]
