# Generated by Django 4.0.4 on 2022-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0002_rename_canamount_can_fiscalyear_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canfiscalyear',
            options={'verbose_name_plural': 'CANs (fiscal year)'},
        ),
        migrations.AlterModelOptions(
            name='commonaccountingnumber',
            options={'verbose_name_plural': 'CANs'},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cans', models.ManyToManyField(related_name='contracts', to='ops_site.commonaccountingnumber')),
            ],
        ),
    ]
