# Generated by Django 4.0.4 on 2022-06-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0003_alter_canfiscalyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ops_site.contract')),
            ],
        ),
    ]
