# Generated by Django 3.2.6 on 2021-09-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0005_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='division',
            field=models.CharField(choices=[('1', 'DCFD'), ('2', 'DDI'), ('3', 'DEI'), ('4', 'DFS'), ('5', 'OD')], max_length=5),
        ),
    ]
