# Generated by Django 3.2.6 on 2021-09-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0006_alter_person_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('purpose', models.TextField()),
                ('arrangement_type', models.CharField(choices=[('1', 'OPRE Appropriation'), ('2', 'Cost Share'), ('3', 'IAA'), ('4', 'IDDA'), ('5', 'MOU')], max_length=30)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizer', to='ops_site.agency')),
                ('source', models.ManyToManyField(to='ops_site.Agency')),
            ],
        ),
    ]
