# Generated by Django 3.2.6 on 2021-09-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0006_alter_person_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('arrangement_type', models.CharField(choices=[('1', 'OPRE Appropriation'), ('2', 'Cost Share'), ('3', 'IAA'), ('4', 'IDDA'), ('5', 'MOU')], max_length=30)),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizer', to='ops_site.agency')),
                ('source', models.ManyToManyField(to='ops_site.Agency')),
            ],
            options={
                'verbose_name_plural': 'CANs',
            },
        ),
        migrations.CreateModel(
            name='CANAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=5)),
                ('amount_available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_budgeted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_amount_anticipated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('can', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops_site.caninfo')),
                ('team_leader', models.ForeignKey(limit_choices_to={'roles__name': 'Team Leader'}, on_delete=django.db.models.deletion.PROTECT, to='ops_site.person')),
            ],
            options={
                'verbose_name_plural': 'CAN Financials',
                'unique_together': {('can', 'fiscal_year')},
            },
        ),
    ]
