# Generated by Django 3.2.6 on 2021-09-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0007_caninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.DateField()),
                ('amount_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_budgeted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_amount_anticipated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('can', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops_site.caninfo')),
                ('team_leader', models.ForeignKey(limit_choices_to={'roles__name': 'Team Leader'}, on_delete=django.db.models.deletion.PROTECT, to='ops_site.person')),
            ],
            options={
                'unique_together': {('can', 'fiscal_year')},
            },
        ),
    ]
