# Generated by Django 3.2.6 on 2021-09-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0008_canamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caninfo',
            name='purpose',
            field=models.TextField(null=True),
        ),
    ]
