# Generated by Django 3.2.6 on 2021-09-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0009_alter_caninfo_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caninfo',
            options={'verbose_name_plural': 'CANs Info'},
        ),
    ]
