# Generated by Django 3.2.6 on 2021-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_site', '0010_alter_caninfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canamount',
            name='fiscal_year',
            field=models.CharField(max_length=5),
        ),
    ]
