flowchart LR
    User(User)--1. User visits site-->Web(OPS Frontend)
    Web --2. Does user have an active token?--> Session{Active Token?}
    Session--2a. Yes - Goto 8-->Web
    Session--2b. No-->Login(Login.gov)
    Login--3. Auth-Code-->Web
    Web--4. Auth-Code-->API(OPS Backend)
    API--5. JWT Auth-Code-->Login
    Login--6. Auth-Token-->API
    API--7. JWT-Session-->Web
    Web--8. JWT-Session-->User
