sequenceDiagram

    Actor User
    participant GUI
    participant API
    participant Database

    Note left of User: Pre-condition: User is logged in,<br/> and has permissions
    User->>+GUI: Navigate to <br/>/agreements/approve/{id}

    GUI->>+API: GET <br/>/agreements/approve/{id}

    API ->>+ Database: SELECT agreements
    Database ->>- API: {agreements}

    API ->>- GUI: SET (RTK) /agreements
    Note over API,GUI: Includes BLI Data

    #Frontend (JS) Checks
    GUI ->> GUI: Check Permissions for<br/>"Send to Approval" button
    GUI ->> GUI: Data validation check

    GUI ->>- User: {page render}

    User ->>+ GUI: User selects BLI-Action <br/> (Draft <--> Planned)
    GUI ->>+ API: GET <br/> /cans?agreementId={id}
    API ->>+ Database: SELECT cans
    Database ->>- API: {cans}
    API ->>- GUI: SET (RTK) /cans

    GUI ->>+ API: GET <br/> /portfolios?can_id={id}
    API ->>+ Database: SELECT portfolios
    Database ->>- API: {portfolios}
    API ->>- GUI: SET (RTK) /portfolios

    GUI ->> GUI: Filter BLI list
    GUI ->> GUI: Update Labels, <br/> Page Context

    GUI ->>- User: {page render}

    User ->> GUI: User Selects BLI <br/> for approval (checkboxes)
    User ->> GUI: User enters "Notes"
    User ->>+ GUI: User Clicks "Send to Approval"

    GUI ->>+ API: Submit BLI <br/> for approval <br/> (POST /bli-packages)

    API ->> API: WorkflowInstance Lookup

    API ->>+ Database: INSERT WorkflowInstance, <br/> WorkflowStepInstance, <br/> BliPackage, <br/>BliPackageSnapshot,
    Database ->>- API: {...id(s)}

    API ->> API: Create Event: <br/>BliPackage Submission
    API ->>+ Database: INSERT Event: BliPackage
    Database ->>- API: SUCCESS: {event.id}

    API ->> API: Create Notification
    API ->>+ Database: INSERT Notification
    Database ->>- API: SUCCESS: {notification.id}

    API ->>- GUI: SET (RTK) /bli-package-metadata <br/>(submission ID?)
    GUI ->>- User: {page render} - <br/> BLI is now in "In-Review" state
