export const AGREEMENTS = [
    {
        id: 1,
        name: "Using Innovative Data to Explore Racial and Ethnic Disparities in Human Services",
        description:
            "This will be a contract to continue planned analyses to explore racial and ethnic disparities in Human Services.",
        agreement_type: "CONTRACT",
        project_officer: "Ivelisse Martinez-Beck",
        period_of_performance_start: "2021-01-01",
        period_of_performance_end: "2021-12-31",
        cans: [], // not sure we need this?
        procurement_shop: {
            id: 2,
            name: "Government Contracting Services",
            fee: 0,
        },
        budget_line_items: [
            {
                id: 123456,
                line_description: "LI 1",
                comments: "",
                can_id: 5,
                can_number: "G994426",
                agreement_id: 1,
                amount: 1000000.0,
                status: "EXECUTING",
                date_needed: "2111-1-11",
                psc_fee_amount: 0,
                created_by: "Carolyn Hsu", // modified number to full name
                created_on: "2023-4-11",
                updated_on: "2023-4-15",
            },
            {
                id: 123457,
                line_description: "LI 2",
                comments: "",
                can_id: 5,
                can_number: "G994426",
                agreement_id: 1,
                amount: 1000000.0,
                status: "OBLIGATED",
                date_needed: "2222-2-22",
                psc_fee_amount: 0,
                created_by: "Carolyn Hsu", // modified number to full name
                created_on: "2023-4-11",
                updated_on: "2023-4-15",
            },
            {
                id: 123458,
                line_description: "LI 3",
                comments: "",
                can_id: 5,
                can_number: "G994426",
                agreement_id: 1,
                amount: 1000000.0,
                status: "PLANNED",
                date_needed: "2333-3-13",
                psc_fee_amount: 0,
                created_by: "Carolyn Hsu", // modified number to full name
                created_on: "2023-4-11",
                updated_on: "2023-4-15",
            },
        ],
    },
    {
        id: 2,
        name: "Using Research to Improve the Lives of Children and Families",
        description: "This will be a contract to improve the lives of children and families.",
        agreement_type: "CONTRACT",
        project_officer: "Carolyn Hsu",
        period_of_performance_start: "2021-01-01",
        period_of_performance_end: "2021-12-31",
        cans: [],
        budget_line_items: [],
    },
    {
        id: 3,
        name: "Using Inner City Data to Improve the Lives of Communities",
        description: "This will be a grant to improve the lives of communities.",
        agreement_type: "GRANT",
        project_officer: "John Smith",
        period_of_performance_start: "2021-01-01",
        period_of_performance_end: "2021-12-31",
        cans: [],
        budget_line_items: [],
    },
    {
        id: 4,
        name: "Using Traffic Data to Improve Self-Driving Cars",
        description: "This will be a direct allocation to improve self-driving cars.",
        agreement_type: "DIRECT_ALLOCATION",
        project_officer: "Jonathon Fong",
        period_of_performance_start: "2021-01-01",
        period_of_performance_end: "2021-12-31",
        cans: [],
        budget_line_items: [],
    },
    {
        id: 5,
        name: "Using Farm Data to Improve the Lives of Farmers",
        description: "This is an IAA to improve the lives of farmers.",
        agreement_type: "IAA",
        project_officer: "Beck Martinez",
        period_of_performance_start: "2021-01-01",
        period_of_performance_end: "2021-12-31",
        cans: [],
        budget_line_items: [],
    },
];
