flowchart LR

    classDef startend fill:#FFF59D,stroke:#333,stroke-width:2px;
    classDef doc fill:#FFECB3,stroke:#333,stroke-width:2px;
    classDef validation fill:#C8E6C9,stroke:#333,stroke-width:2px;
    classDef approval fill:#BBDEFB,stroke:#333,stroke-width:2px;

    Start[START]:::startend
    End[END]:::startend
    doc1(Document 1):::doc
    doc2(Document 2):::doc
    doc3(Document 3):::doc
    val1((Validate Doc 1)):::validation
    val2((Validate Doc 2)):::validation
    val3((Validate Doc 3)):::validation
    final_approval[Final Approval Step]:::approval

    %% Document Uploads
    subgraph step1 ["Document Uploads [DOCUMENT_MGMT]"]
        doc1 --> val1
        doc2 --> val2
        doc3 --> val3
    end

    %% Final Approval
    subgraph step2 ["Final Step [APPROVAL]"]
        final_approval
    end


    Start --> step1
    step1 --> step2
    step2 --> End
