classDiagram
    class WorkflowTemplate {
        +String name
        +List steps
    }

    class WorkflowInstance {
        +Integer associated_id
        +Enum associated_type
        +Integer workflow_template_id
        +Enum workflow_action
        +Integer current_workflow_step_instance_id
        +List steps
    }

    class WorkflowStepTemplate {
        +String name
        +Integer workflow_template_id
        +Enum workflow_type
        +Integer index
        +List step_approvers
    }

    class WorkflowStepInstance {
        +Integer workflow_instance_id
        +Integer workflow_step_template_id
        +Enum status
        +String notes
        +DateTime time_started
        +DateTime time_completed
        +List successor_dependencies
        +List predecessor_dependencies
    }

    class WorkflowStepDependency {
        +Integer predecessor_step_id
        +Integer successor_step_id
    }

    class StepApprovers {
        +Integer workflow_step_template_id
        +Integer user_id
        +Integer role_id
        +Integer group_id
    }

    class Package {
        +Integer submitter_id
        +Integer workflow
        +String notes
        +List package_snapshots
    }

    class PackageSnapshot {
        +Integer _package_id
        +Integer version
        +Integer bli_id
    }

    WorkflowTemplate "1" -- "0..*" WorkflowStepTemplate : steps
    WorkflowInstance "1" -- "0..*" WorkflowStepInstance : steps
    WorkflowStepTemplate "1" -- "0..*" StepApprovers : step_approvers
    WorkflowStepInstance "1" -- "1" WorkflowStepDependency : successor_dependencies
    WorkflowStepInstance "1" -- "1" WorkflowStepDependency : predecessor_dependencies
    Package "1" -- "0..*" PackageSnapshot : package_snapshots

    WorkflowStepDependency "1" -- "1" WorkflowStepInstance : predecessor_step
    WorkflowStepDependency "1" -- "1" WorkflowStepInstance : successor_step

    WorkflowInstance "*" -- "1" WorkflowTemplate : workflow_template
    WorkflowStepInstance "*" -- "1" WorkflowStepTemplate : workflow_step_template
    Package "*" -- "1" WorkflowInstance : workflow
