classDiagram

    class WorkflowType {
        APPROVAL
        DOCUMENT_MGMT
        VALIDATION
    }

    class WorkflowStatus {
        REVIEW
        APPROVED
        REJECTED
        CHANGES
    }

    class WorkflowTemplate {
        +id: Integer
        name: String
        workflow_type: WorkflowType
    }

    class WorkflowInstance {
        +id: Integer
        associated_id: Integer
        associated_type: String
        workflow_template_id: Integer
    }

    class WorkflowStepTemplate {
        +id: Integer
        name: String
        workflow_type: WorkflowType
        index: Integer
        workflow_template_id: Integer
    }

    class WorkflowStepInstance {
        +id: Integer
        workflow_instance_id: Integer
        workflow_step_template_id: Integer
        status: WorkflowStatus
        notes: String
        time_completed: DateTime
    }

    class WorkflowStepDependency {
        predecessor_step_id: Integer
        successor_step_id: Integer
    }

    class StepApprovers {
        +id: Integer
        workflow_step_template_id: Integer
        user_id: Integer
        role_id: Integer
        group_id: Integer
    }

    class Package {
        +id: Integer
        workflow_instance_id: Integer


    }

    WorkflowTemplate "1" -- "0..*" WorkflowStepTemplate: steps
    WorkflowTemplate "1" -- "0..*" WorkflowInstance
    WorkflowInstance "1" -- "0..*" WorkflowStepInstance: steps
    WorkflowStepTemplate "1" -- "0..*" StepApprovers: step_approvers
    WorkflowStepInstance "1" -- "0..*" WorkflowStepDependency: predecessor_dependencies
    WorkflowStepInstance "1" -- "0..*" WorkflowStepDependency: successor_dependencies
    WorkflowStepInstance --> WorkflowStatus: has_status
    WorkflowStepTemplate --> WorkflowType: has_type

    class USER {
        +Integer id
        '...' other_attributes
    }

    class ROLE {
        +Integer id
        '...' other_attributes
    }

    class GROUP {
        +Integer id
        '...' other_attributes
    }

    USER "0..*" --> "0..*" StepApprovers: approves
    ROLE "0..*" --> "0..*" StepApprovers: approves
    GROUP "0..*" --> "0..*" StepApprovers: approves
