flowchart LR
    %% Styles
    classDef startend fill:#FFF59D,stroke:#333,stroke-width:2px;
    classDef doc fill:#FFECB3,stroke:#333,stroke-width:2px;
    classDef validation fill:#C8E6C9,stroke:#333,stroke-width:2px;
    classDef approval fill:#BBDEFB,stroke:#333,stroke-width:2px;

    %% Sequential Steps
    Start[START]:::startend
    End[END]:::startend
    rev1(review):::doc
    rev2(review):::doc
    approval1((Approve)):::approval
    approval2((Approve)):::approval
    agreement{{Agreeement::<br/>Draft}}
    agreement2{{Agreeement::<br/>Planned}}


    %% Document Uploads
    subgraph step1 ["Team Lead Review [APPROVAL]"]
        rev1 --> approval1
    end

    %% Final Approval
    subgraph step2 ["Division Director [APPROVAL]"]
        rev2 --> approval2
    end

    agreement --> Start
    Start --> step1
    step1 --> step2
    step2 --> End
    End --> agreement2


    %% Parallel Steps
    Start2[START]:::startend
    End2[END]:::startend
    rev12(review):::doc
    rev22(review):::doc
    approval12((Approve)):::approval
    approval22((Approve)):::approval
    agreement12{{Agreeement::<br/>Draft}}
    agreement22{{Agreeement::<br/>Planned}}

    %% Document Uploads
    subgraph step12 ["Team Lead Review [APPROVAL]"]
        rev12 --> approval12
    end

    %% Final Approval
    subgraph step22 ["Team Lead #2 [APPROVAL]"]
        rev22 --> approval22
    end

    agreement12 --> Start2
    Start2 --> step12
    Start2 --> step22
    step12 --> check{Check Workflow<br/>Status}
    step22 --> check
    check --> End2
    End2 --> agreement22
