name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Semgrep Analyze
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:67319956da3dcb58baf5b322899c15458e3963e7018a86aeeb5cd224e69cb77a # 1.47.0
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      # We've changed the behavior a little, instead of forcing a fail on `semgrep scan` step
      # we force the upload, and manage any results in the sencondary CodeQL Analysis of the
      # uploaded files. Configuration is handled in Settings --> Security --> CodeQL
      - name: Semgrep Scan
        run: |
          echo "SEMGREP_TO_UPLOAD=semgrep.sarif" >> $GITHUB_ENV
          semgrep scan --sarif --output=semgrep.sarif --exclude="frontend/src/uswds" --metrics=off
        env:
          SEMGREP_RULES: "p/default"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4
        with:
          sarif_file: ${{ env.SEMGREP_TO_UPLOAD }}
        if: always()
