name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Semgrep Analyze
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:9fb6f44dc162b1e0aada85f072a95141844c61e3bfcedf40b8a46fecf208e986 # 1.47.0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # We've changed the behavior a little, instead of forcing a fail on `semgrep scan` step
      # we force the upload, and manage any results in the sencondary CodeQL Analysis of the
      # uploaded files. Configuration is handled in Settings --> Security --> CodeQL
      - name: Semgrep Scan
        run: |
          echo "SEMGREP_TO_UPLOAD=semgrep.sarif" >> $GITHUB_ENV
          semgrep scan --sarif --output=semgrep.sarif --exclude="frontend/src/uswds" --metrics=off
        env:
          SEMGREP_RULES: "p/default"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4
        with:
          sarif_file: ${{ env.SEMGREP_TO_UPLOAD }}
        if: always()
