name: Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    permissions:
      security-events: write
    name: Semgrep Analyze
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:2b33f46ba66cf8cc2ad59ccfa7d22951fd00c632c38f1339e84ec8e6e641a942 # 1.47.0
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      # We've changed the behavior a little, instead of forcing a fail on `semgrep scan` step
      # we force the upload, and manage any results in the sencondary CodeQL Analysis of the
      # uploaded files. Configuration is handled in Settings --> Security --> CodeQL
      - name: Semgrep Scan
        run: |
          echo "SEMGREP_TO_UPLOAD=semgrep.sarif" >> $GITHUB_ENV
          semgrep scan --sarif --output=semgrep.sarif --exclude="frontend/src/uswds" --metrics=off
        env:
          SEMGREP_RULES: "p/default"

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          sarif_file: ${{ env.SEMGREP_TO_UPLOAD }}
        if: always()
