# This file was initially generated by terraspace_plugin_azurerm 0.7.0
# Backend Config Variables Docs
# https://terraspace.cloud/docs/config/backend/variables/
#
# SUBSCRIPTION_HASH is a short 4-char consistent hash of the longer subscription id.
# LOCATION_HASH is a short 4-char consistent hash of the longer location.
# This is useful because azure storage account names are not allowed special characters and are limited to 24 chars.
terraform {
  backend "azurerm" {
    resource_group_name  = "tf-ops-dev-eastus"
    storage_account_name = "tfc62976c745e7dev"
    container_name       = "terraform-state"
    key                  = "main/eastus/ops/dev/stacks/data-tools/terraform.tfstate"
  }
}
