export const data = [
    {
        id: 1,
        name: "Center for Research on Learning and Teaching",
        link: "/projects/1",
        type: "research",
        funding: "6000000",
        fundingToDate: "1900000",
        firstAwardDate: "2018-01-01",
        cans: "3",
        agreement: "Grant",
    },
    {
        id: 2,
        name: "Project Two that is kinda long",
        link: "/projects/2",
        type: "research",
        funding: "8000000",
        fundingToDate: "1000000",
        firstAwardDate: "2020-01-01",
        cans: "2",
        agreement: "Mixed",
    },
    {
        id: 3,
        name: "Project Three that is kinda long",
        link: "/projects/3",
        type: "research",
        funding: "1000000",
        fundingToDate: "0",
        firstAwardDate: "2022-01-01",
        cans: "1",
        agreement: "Contract",
    },
    {
        id: 4,
        name: "OPRE Website Development",
        link: "/projects/4",
        type: "admin_and_support",
        funding: "1000000",
        fundingToDate: "0",
        firstAwardDate: "2022-01-01",
        cans: "4",
        agreement: "Contract",
    },
    {
        id: 5,
        name: "OPRE OPS",
        link: "/projects/5",
        type: "admin_and_support",
        funding: "0",
        fundingToDate: "1000000",
        firstAwardDate: "2022-01-01",
        cans: "5",
        agreement: "Contract",
    },
];
